//! GENERATED by `python3 scripts/riscv_operand_classes.py emit` -- do not edit.
//!
//! Sail-derived operand-class corpus, group `flow` (17 cases).
//! Every expected value below is an output of the pinned Sail model
//! observed over RVFI-DII at generation time; consuming tests replay
//! the body and compare, they do not re-derive semantics.
//!
//! Generation authority:
//!   model     riscv/sail-riscv@8c7f2da58de0ba5e4457e4de07e0046f0439f35f
//!   tag       2026-07-20-8c7f2da, compiler 0.20.2
//!   transport RVFI-DII v1, entry patch sha256 1309655496ea8c8aae3cade751b1ba695dd19b2048f6118d28371be693dbb734
//! The binary hash is omitted deliberately: sail_riscv_sim builds are
//! not bit-reproducible, and identity is the pinned source revision
//! plus build-info strings, which `riscv_equivalence.verify_sail_binary`
//! checked before a single case was observed.

const data = @import("../operand_classes.zig");

pub const cases = [_]data.Case{
    .{ .name = "jal/jump_link", .op = .JAL, .class = .jump_link, .body = &.{ 0x0080056f, 0x00100e13, 0x00200e93 }, .under_test = 0, .retired = &.{ 0, 2 }, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 4, .rd_pc_relative = true, .next_pc_offset = 8 }} },
    .{ .name = "jal/jump_discard_link", .op = .JAL, .class = .jump_discard_link, .body = &.{ 0x0080006f, 0x00100e13, 0x00200e93 }, .under_test = 0, .retired = &.{ 0, 2 }, .checks = &.{.{ .index = 0, .rd = 0, .rd_value = 0, .next_pc_offset = 8 }} },
    .{ .name = "jal/jump_backward", .op = .JAL, .class = .jump_backward, .body = &.{ 0x00c0006f, 0x00100e13, 0x0080006f, 0xff9ff56f }, .under_test = 3, .retired = &.{ 0, 3, 1, 2 }, .checks = &.{.{ .index = 3, .rd = 10, .rd_value = 4, .rd_pc_relative = true, .next_pc_offset = 0xfffffff8 }} },
    .{ .name = "jalr/jump_link", .op = .JALR, .class = .jump_link, .rs1_pc_derived = true, .body = &.{ 0x00000317, 0x00c30567, 0x00100e13, 0x00200e93 }, .under_test = 1, .retired = &.{ 0, 1, 3 }, .checks = &.{.{ .index = 1, .rd = 10, .rd_value = 4, .rd_pc_relative = true, .next_pc_offset = 8 }} },
    .{ .name = "jalr/jalr_lsb_clear", .op = .JALR, .class = .jalr_lsb_clear, .rs1_pc_derived = true, .body = &.{ 0x00000317, 0x00d30567, 0x00100e13, 0x00200e93 }, .under_test = 1, .retired = &.{ 0, 1, 3 }, .checks = &.{.{ .index = 1, .rd = 10, .rd_value = 4, .rd_pc_relative = true, .next_pc_offset = 8 }} },
    .{ .name = "jalr/jump_discard_link", .op = .JALR, .class = .jump_discard_link, .rs1_pc_derived = true, .body = &.{ 0x00000317, 0x00c30067, 0x00100e13, 0x00200e93 }, .under_test = 1, .retired = &.{ 0, 1, 3 }, .checks = &.{.{ .index = 1, .rd = 0, .rd_value = 0, .next_pc_offset = 8 }} },
    .{ .name = "jalr/rd_equals_rs1", .op = .JALR, .class = .rd_equals_rs1, .rs1_pc_derived = true, .body = &.{ 0x00000317, 0x00c30367, 0x00100e13, 0x00200e93 }, .under_test = 1, .retired = &.{ 0, 1, 3 }, .checks = &.{.{ .index = 1, .rd = 6, .rd_value = 4, .rd_pc_relative = true, .next_pc_offset = 8 }} },
    .{ .name = "jalr/jump_backward", .op = .JALR, .class = .jump_backward, .rs1_pc_derived = true, .body = &.{ 0x00c0006f, 0x00100e13, 0x00c0006f, 0x00000317, 0xff830567 }, .under_test = 4, .retired = &.{ 0, 3, 4, 1, 2 }, .checks = &.{.{ .index = 4, .rd = 10, .rd_value = 4, .rd_pc_relative = true, .next_pc_offset = 0xfffffff4 }} },
    .{ .name = "lui/upper_imm_zero", .op = .LUI, .class = .upper_imm_zero, .body = &.{0x00000537}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0 }} },
    .{ .name = "lui/upper_imm_one", .op = .LUI, .class = .upper_imm_one, .body = &.{0x00001537}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0x00001000 }} },
    .{ .name = "lui/upper_imm_sign_bit", .op = .LUI, .class = .upper_imm_sign_bit, .body = &.{0x80000537}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0x80000000 }} },
    .{ .name = "lui/upper_imm_all_ones", .op = .LUI, .class = .upper_imm_all_ones, .body = &.{0xfffff537}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0xfffff000 }} },
    .{ .name = "lui/rd_x0_discard", .op = .LUI, .class = .rd_x0_discard, .body = &.{0xabcde037}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 0, .rd_value = 0 }} },
    .{ .name = "auipc/upper_imm_zero", .op = .AUIPC, .class = .upper_imm_zero, .body = &.{0x00000517}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0, .rd_pc_relative = true }} },
    .{ .name = "auipc/upper_imm_sign_bit", .op = .AUIPC, .class = .upper_imm_sign_bit, .body = &.{0x80000517}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0x80000000, .rd_pc_relative = true }} },
    .{ .name = "auipc/auipc_pc_wrap", .op = .AUIPC, .class = .auipc_pc_wrap, .body = &.{0xfffff517}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 10, .rd_value = 0xfffff000, .rd_pc_relative = true }} },
    .{ .name = "fence/fence_nop", .op = .FENCE, .class = .fence_nop, .body = &.{0x0ff0000f}, .under_test = 0, .retired = &.{0}, .checks = &.{.{ .index = 0, .rd = 0, .rd_value = 0 }} },
};
