"""Resolve active Native Rust tool module and local Cargo edges.

Cargo TOML is parsed structurally. Static ``mod name;``, ``#[path] mod``, and
absolute ``use crate::...`` edges are resolved; macro-generated modules and
conditional source generated by build scripts remain Cargo/test concerns.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

from . import policy
from .common import contained_path, cycle_nodes
from .model import Finding


MOD_RE = re.compile(
    r'^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+([A-Za-z_][A-Za-z0-9_]*)\s*;',
    re.MULTILINE,
)
PATH_MOD_RE = re.compile(
    r'^\s*#\s*\[\s*path\s*=\s*"([^"\n]+)"\s*\]\s*'
    r'(?:pub(?:\([^)]*\))?\s+)?mod\s+([A-Za-z_][A-Za-z0-9_]*)\s*;',
    re.MULTILINE,
)
CRATE_USE_RE = re.compile(
    r'^\s*(?:pub(?:\([^)]*\))?\s+)?use\s+crate::([A-Za-z_][A-Za-z0-9_:]*)',
    re.MULTILINE,
)


def dependency_tables(payload: object) -> list[dict[str, object]]:
    tables: list[dict[str, object]] = []
    if not isinstance(payload, dict):
        return tables
    for key, value in payload.items():
        if key in {"dependencies", "dev-dependencies", "build-dependencies"} and isinstance(value, dict):
            tables.append(value)
        elif isinstance(value, dict):
            tables.extend(dependency_tables(value))
    return tables


def module_target(source: Path, name: str, explicit: str | None = None) -> Path | None:
    if explicit is not None:
        candidates = [source.parent / explicit]
    else:
        base = (
            source.parent
            if source.name in {"main.rs", "lib.rs", "mod.rs"}
            else source.parent / source.stem
        )
        candidates = [base / f"{name}.rs", base / name / "mod.rs"]
    return next((candidate.resolve() for candidate in candidates if candidate.is_file()), None)


def scan_cargo(repo: Path, crate: Path, crate_name: str) -> tuple[list[Finding], bool]:
    manifest = crate / "Cargo.toml"
    try:
        payload = tomllib.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        return [Finding(
            f"cargo-manifest:tools/{crate_name}/Cargo.toml",
            f"tools/{crate_name}/Cargo.toml: cannot parse active Native tool manifest ({error})",
        )], False
    findings: list[Finding] = []
    for table in dependency_tables(payload):
        for dependency, specification in table.items():
            if not isinstance(specification, dict) or not isinstance(specification.get("path"), str):
                continue
            target = (crate / specification["path"]).resolve()
            target_relative = contained_path(target, repo)
            if target_relative is not None and contained_path(target, crate) is None:
                findings.append(Finding(
                    f"cargo-dependency:tools/{crate_name}->{target_relative.as_posix()}",
                    f"tools/{crate_name}/Cargo.toml: Native Rust tool must remain independently buildable ({dependency})",
                ))
    return findings, True


def scan_modules(repo: Path, crate: Path, crate_name: str) -> list[Finding]:
    source_root = crate / "src"
    root = source_root / "main.rs"
    if not root.is_file():
        root = source_root / "lib.rs"
    if not root.is_file():
        return [Finding(
            f"rust-root:tools/{crate_name}",
            f"tools/{crate_name}: active Native Rust tool has no src/main.rs or src/lib.rs",
        )]

    root_modules = set(MOD_RE.findall(root.read_text(encoding="utf-8")))
    findings: list[Finding] = []
    modules: dict[str, Path] = {}
    pending = [(name, root) for name in sorted(root_modules)]
    while pending:
        name, owner = pending.pop()
        owner_text = owner.read_text(encoding="utf-8")
        explicit_modules = {child: path for path, child in PATH_MOD_RE.findall(owner_text)}
        short_name = name.rpartition("::")[2]
        target = module_target(owner, short_name, explicit_modules.get(short_name))
        if target is None or contained_path(target, source_root) is None:
            findings.append(Finding(
                f"rust-module:{owner.relative_to(repo).as_posix()}->{short_name}",
                f"{owner.relative_to(repo)}: declared Rust module must resolve inside the crate source root ({short_name})",
            ))
            continue
        if name in modules:
            continue
        modules[name] = target
        for child in sorted(set(MOD_RE.findall(target.read_text(encoding="utf-8")))):
            pending.append((f"{name}::{child}", target))

    graph: dict[str, set[str]] = {name: set() for name in modules}
    for name, source in modules.items():
        for imported in CRATE_USE_RE.findall(source.read_text(encoding="utf-8")):
            parts = imported.split("::")
            target_name = next((
                "::".join(parts[:length])
                for length in range(len(parts), 0, -1)
                if "::".join(parts[:length]) in modules
            ), None)
            if target_name is not None and target_name != name:
                graph[name].add(target_name)
    for name in sorted(cycle_nodes(graph)):
        findings.append(Finding(
            f"rust-cycle:tools/{crate_name}/src/{name}",
            f"tools/{crate_name}/src/{name}: Native Rust modules participate in a dependency cycle",
        ))
    return findings


def scan(repo: Path) -> list[Finding]:
    findings: list[Finding] = []
    for crate_name in sorted(policy.ACTIVE_NATIVE_RUST_CRATES):
        crate = repo / "tools" / crate_name
        if not crate.is_dir():
            continue
        cargo_findings, parsed = scan_cargo(repo, crate, crate_name)
        findings.extend(cargo_findings)
        if parsed:
            findings.extend(scan_modules(repo, crate, crate_name))
    return findings
