"""Public helpers for the Native CPU/Metal proof matrix controller."""

from .artifacts import (
    atomic_write_bytes,
    atomic_write_json,
    load_proof_artifact,
    output_dir_lock,
    require_unprofiled_environment,
    run_lane,
    run_rust_oracle,
)
from .contract import validate_pair, validate_proof_artifact, validate_report
from .controller import run_matrix
from .evidence import MIN_FORMAL_MEASURED_PROOFS, SUMMARY_PROTOCOL
from .model import (
    BACKEND_COUNTER_KEYS,
    DEFAULT_COOLDOWN_SECONDS,
    DEFAULT_PROTOCOL,
    DEFAULT_WARMUPS,
    DEFAULT_WORKLOADS,
    LIBRARY_PREPARATION_SECONDS_KEY,
    MAX_COMMITTED_TRACE_CELLS,
    MIN_HEADLINE_WARMUPS,
    MatrixError,
    PIPELINE_CACHE_COUNTER_KEYS,
    PIPELINE_CACHE_SECONDS_KEY,
    RUST_ORACLE_SHA256,
    RUNTIME_ADMISSION_KEYS,
    SESSION_KEYS,
    Workload,
    parse_workload,
    validate_workload,
    workload_descriptor_sha256,
)

__all__ = [
    "BACKEND_COUNTER_KEYS",
    "DEFAULT_COOLDOWN_SECONDS",
    "DEFAULT_PROTOCOL",
    "DEFAULT_WARMUPS",
    "DEFAULT_WORKLOADS",
    "LIBRARY_PREPARATION_SECONDS_KEY",
    "MAX_COMMITTED_TRACE_CELLS",
    "MIN_HEADLINE_WARMUPS",
    "MIN_FORMAL_MEASURED_PROOFS",
    "MatrixError",
    "PIPELINE_CACHE_COUNTER_KEYS",
    "PIPELINE_CACHE_SECONDS_KEY",
    "RUST_ORACLE_SHA256",
    "RUNTIME_ADMISSION_KEYS",
    "SESSION_KEYS",
    "SUMMARY_PROTOCOL",
    "Workload",
    "atomic_write_bytes",
    "atomic_write_json",
    "load_proof_artifact",
    "output_dir_lock",
    "parse_workload",
    "run_lane",
    "run_matrix",
    "run_rust_oracle",
    "require_unprofiled_environment",
    "validate_pair",
    "validate_proof_artifact",
    "validate_report",
    "validate_workload",
    "workload_descriptor_sha256",
]
