"""Public helpers for the Native CPU/Metal proof matrix controller."""

from .artifacts import (
    atomic_write_bytes,
    atomic_write_json,
    load_proof_artifact,
    output_dir_lock,
    require_unprofiled_environment,
    run_lane,
    run_rust_oracle,
)
from .contract import validate_pair, validate_proof_artifact, validate_report
from .controller import run_matrix
from .evidence import MIN_FORMAL_MEASURED_PROOFS, SUMMARY_PROTOCOL
from .model import (
    ARCHIVE_STORE_COUNTER_KEYS,
    ARCHIVE_STORE_SECONDS_KEY,
    BACKEND_COUNTER_KEYS,
    DEFAULT_COOLDOWN_SECONDS,
    DEFAULT_PROTOCOL,
    DEFAULT_WARMUPS,
    DEFAULT_WORKLOADS,
    HOLISTIC_SUITE,
    LIBRARY_PREPARATION_SECONDS_KEY,
    MAX_COMMITTED_TRACE_CELLS,
    MIN_HEADLINE_WARMUPS,
    MatrixError,
    PIPELINE_CACHE_COUNTER_KEYS,
    PIPELINE_CACHE_SECONDS_KEY,
    REPORT_SCHEMA_VERSION,
    RUST_ORACLE_SHA256,
    RUNTIME_ADMISSION_KEYS,
    SESSION_KEYS,
    WORKLOAD_SUITES,
    SuiteRow,
    Workload,
    WorkloadSuite,
    parse_workload,
    validate_suite,
    validate_workload,
    workload_descriptor_sha256,
)
from .resource_admission import (
    ACCOUNTED_BYTES_PER_COMMITTED_CELL,
    RESOURCE_PROFILES,
    ZIG_RESOURCE_AUTHORITY,
    ZIG_RESOURCE_CONSTANTS,
    resource_limits,
    validate_source_contract,
)

__all__ = [
    "ARCHIVE_STORE_COUNTER_KEYS",
    "ARCHIVE_STORE_SECONDS_KEY",
    "ACCOUNTED_BYTES_PER_COMMITTED_CELL",
    "BACKEND_COUNTER_KEYS",
    "DEFAULT_COOLDOWN_SECONDS",
    "DEFAULT_PROTOCOL",
    "DEFAULT_WARMUPS",
    "DEFAULT_WORKLOADS",
    "HOLISTIC_SUITE",
    "LIBRARY_PREPARATION_SECONDS_KEY",
    "MAX_COMMITTED_TRACE_CELLS",
    "MIN_HEADLINE_WARMUPS",
    "MIN_FORMAL_MEASURED_PROOFS",
    "MatrixError",
    "PIPELINE_CACHE_COUNTER_KEYS",
    "PIPELINE_CACHE_SECONDS_KEY",
    "REPORT_SCHEMA_VERSION",
    "RESOURCE_PROFILES",
    "RUST_ORACLE_SHA256",
    "RUNTIME_ADMISSION_KEYS",
    "SESSION_KEYS",
    "SUMMARY_PROTOCOL",
    "SuiteRow",
    "WORKLOAD_SUITES",
    "Workload",
    "WorkloadSuite",
    "ZIG_RESOURCE_AUTHORITY",
    "ZIG_RESOURCE_CONSTANTS",
    "atomic_write_bytes",
    "atomic_write_json",
    "load_proof_artifact",
    "output_dir_lock",
    "parse_workload",
    "run_lane",
    "run_matrix",
    "run_rust_oracle",
    "require_unprofiled_environment",
    "resource_limits",
    "validate_pair",
    "validate_proof_artifact",
    "validate_report",
    "validate_suite",
    "validate_source_contract",
    "validate_workload",
    "workload_descriptor_sha256",
]
