//! Version-pinned Cairo claim registry.
//!
//! Generated by `scripts/generate_cairo_claim_registry.py`; do not edit by hand.

const std = @import("std");

pub const SourceRevision = struct {
    stwo_cairo: []const u8,
    stwo: []const u8,
};

pub const SourceFile = struct {
    path: []const u8,
    sha256: []const u8,
};

pub const LogSizeShape = enum {
    dynamic,
    fixed,
    special_dynamic_prefix,
};

pub const ClaimField = struct {
    name: []const u8,
    field_index: u8,
    first_enable_slot: u8,
    enable_slot_count: u8,
    log_size_shape: LogSizeShape,
    fixed_log_size: ?u32,
};

pub const EnableSlot = struct {
    name: []const u8,
    enable_slot: u8,
    claim_field_index: u8,
    field_slot_index: u8,
    log_size_shape: LogSizeShape,
    fixed_log_size: ?u32,
};

pub const source_revision = SourceRevision{
    .stwo_cairo = "82f21252a68ec006d73e299f5bf1ce6d4db0ee78",
    .stwo = "7b211edde786775016ef3eecb837a6240d8fe792",
};
pub const registry_sha256 = "3c2e8432eae05b26dbce0c313ca7fc82f0d3480e6a945cc59b1a83e925518877";
pub const claim_field_count: usize = 68;
pub const enable_slot_count: usize = 83;
pub const memory_id_to_big_enable_slot_count: usize = 16;

pub const claim_fields = [_]ClaimField{
    .{ .name = "add_opcode", .field_index = 0, .first_enable_slot = 0, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_opcode_small", .field_index = 1, .first_enable_slot = 1, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_ap_opcode", .field_index = 2, .first_enable_slot = 2, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode", .field_index = 3, .first_enable_slot = 3, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_imm", .field_index = 4, .first_enable_slot = 4, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_double_deref", .field_index = 5, .first_enable_slot = 5, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_compress_opcode", .field_index = 6, .first_enable_slot = 6, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_abs", .field_index = 7, .first_enable_slot = 7, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_rel_imm", .field_index = 8, .first_enable_slot = 8, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "generic_opcode", .field_index = 9, .first_enable_slot = 9, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_non_taken", .field_index = 10, .first_enable_slot = 10, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_taken", .field_index = 11, .first_enable_slot = 11, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_abs", .field_index = 12, .first_enable_slot = 12, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_double_deref", .field_index = 13, .first_enable_slot = 13, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel", .field_index = 14, .first_enable_slot = 14, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel_imm", .field_index = 15, .first_enable_slot = 15, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode", .field_index = 16, .first_enable_slot = 16, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode_small", .field_index = 17, .first_enable_slot = 17, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "qm_31_add_mul_opcode", .field_index = 18, .first_enable_slot = 18, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ret_opcode", .field_index = 19, .first_enable_slot = 19, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_instruction", .field_index = 20, .first_enable_slot = 20, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round", .field_index = 21, .first_enable_slot = 21, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_g", .field_index = 22, .first_enable_slot = 22, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round_sigma", .field_index = 23, .first_enable_slot = 23, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 4 },
    .{ .name = "triple_xor_32", .field_index = 24, .first_enable_slot = 24, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_bitwise_xor_12", .field_index = 25, .first_enable_slot = 25, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "add_mod_builtin", .field_index = 26, .first_enable_slot = 26, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "bitwise_builtin", .field_index = 27, .first_enable_slot = 27, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_mod_builtin", .field_index = 28, .first_enable_slot = 28, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin", .field_index = 29, .first_enable_slot = 29, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin_narrow_windows", .field_index = 30, .first_enable_slot = 30, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_builtin", .field_index = 31, .first_enable_slot = 31, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check96_builtin", .field_index = 32, .first_enable_slot = 32, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_builtin", .field_index = 33, .first_enable_slot = 33, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ec_op_builtin", .field_index = 34, .first_enable_slot = 34, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_generic", .field_index = 35, .first_enable_slot = 35, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_aggregator_window_bits_18", .field_index = 36, .first_enable_slot = 36, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_18", .field_index = 37, .first_enable_slot = 37, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_18", .field_index = 38, .first_enable_slot = 38, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 23 },
    .{ .name = "pedersen_aggregator_window_bits_9", .field_index = 39, .first_enable_slot = 39, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_9", .field_index = 40, .first_enable_slot = 40, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_9", .field_index = 41, .first_enable_slot = 41, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "poseidon_aggregator", .field_index = 42, .first_enable_slot = 42, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_3_partial_rounds_chain", .field_index = 43, .first_enable_slot = 43, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_full_round_chain", .field_index = 44, .first_enable_slot = 44, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "cube_252", .field_index = 45, .first_enable_slot = 45, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_round_keys", .field_index = 46, .first_enable_slot = 46, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_252_width_27", .field_index = 47, .first_enable_slot = 47, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_address_to_id", .field_index = 48, .first_enable_slot = 48, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_id_to_big", .field_index = 49, .first_enable_slot = 49, .enable_slot_count = 16, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_small", .field_index = 50, .first_enable_slot = 65, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_6", .field_index = 51, .first_enable_slot = 66, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_8", .field_index = 52, .first_enable_slot = 67, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_11", .field_index = 53, .first_enable_slot = 68, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 11 },
    .{ .name = "range_check_12", .field_index = 54, .first_enable_slot = 69, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 12 },
    .{ .name = "range_check_18", .field_index = 55, .first_enable_slot = 70, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_20", .field_index = 56, .first_enable_slot = 71, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "range_check_4_3", .field_index = 57, .first_enable_slot = 72, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 7 },
    .{ .name = "range_check_4_4", .field_index = 58, .first_enable_slot = 73, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_9_9", .field_index = 59, .first_enable_slot = 74, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_7_2_5", .field_index = 60, .first_enable_slot = 75, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "range_check_3_6_6_3", .field_index = 61, .first_enable_slot = 76, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_4_4_4_4", .field_index = 62, .first_enable_slot = 77, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "range_check_3_3_3_3_3", .field_index = 63, .first_enable_slot = 78, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "verify_bitwise_xor_4", .field_index = 64, .first_enable_slot = 79, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "verify_bitwise_xor_7", .field_index = 65, .first_enable_slot = 80, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "verify_bitwise_xor_8", .field_index = 66, .first_enable_slot = 81, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "verify_bitwise_xor_9", .field_index = 67, .first_enable_slot = 82, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
};

pub const enable_slots = [_]EnableSlot{
    .{ .name = "add_opcode", .enable_slot = 0, .claim_field_index = 0, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_opcode_small", .enable_slot = 1, .claim_field_index = 1, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_ap_opcode", .enable_slot = 2, .claim_field_index = 2, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode", .enable_slot = 3, .claim_field_index = 3, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_imm", .enable_slot = 4, .claim_field_index = 4, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_double_deref", .enable_slot = 5, .claim_field_index = 5, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_compress_opcode", .enable_slot = 6, .claim_field_index = 6, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_abs", .enable_slot = 7, .claim_field_index = 7, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_rel_imm", .enable_slot = 8, .claim_field_index = 8, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "generic_opcode", .enable_slot = 9, .claim_field_index = 9, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_non_taken", .enable_slot = 10, .claim_field_index = 10, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_taken", .enable_slot = 11, .claim_field_index = 11, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_abs", .enable_slot = 12, .claim_field_index = 12, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_double_deref", .enable_slot = 13, .claim_field_index = 13, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel", .enable_slot = 14, .claim_field_index = 14, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel_imm", .enable_slot = 15, .claim_field_index = 15, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode", .enable_slot = 16, .claim_field_index = 16, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode_small", .enable_slot = 17, .claim_field_index = 17, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "qm_31_add_mul_opcode", .enable_slot = 18, .claim_field_index = 18, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ret_opcode", .enable_slot = 19, .claim_field_index = 19, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_instruction", .enable_slot = 20, .claim_field_index = 20, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round", .enable_slot = 21, .claim_field_index = 21, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_g", .enable_slot = 22, .claim_field_index = 22, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round_sigma", .enable_slot = 23, .claim_field_index = 23, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 4 },
    .{ .name = "triple_xor_32", .enable_slot = 24, .claim_field_index = 24, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_bitwise_xor_12", .enable_slot = 25, .claim_field_index = 25, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "add_mod_builtin", .enable_slot = 26, .claim_field_index = 26, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "bitwise_builtin", .enable_slot = 27, .claim_field_index = 27, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_mod_builtin", .enable_slot = 28, .claim_field_index = 28, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin", .enable_slot = 29, .claim_field_index = 29, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin_narrow_windows", .enable_slot = 30, .claim_field_index = 30, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_builtin", .enable_slot = 31, .claim_field_index = 31, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check96_builtin", .enable_slot = 32, .claim_field_index = 32, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_builtin", .enable_slot = 33, .claim_field_index = 33, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ec_op_builtin", .enable_slot = 34, .claim_field_index = 34, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_generic", .enable_slot = 35, .claim_field_index = 35, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_aggregator_window_bits_18", .enable_slot = 36, .claim_field_index = 36, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_18", .enable_slot = 37, .claim_field_index = 37, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_18", .enable_slot = 38, .claim_field_index = 38, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 23 },
    .{ .name = "pedersen_aggregator_window_bits_9", .enable_slot = 39, .claim_field_index = 39, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_9", .enable_slot = 40, .claim_field_index = 40, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_9", .enable_slot = 41, .claim_field_index = 41, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "poseidon_aggregator", .enable_slot = 42, .claim_field_index = 42, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_3_partial_rounds_chain", .enable_slot = 43, .claim_field_index = 43, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_full_round_chain", .enable_slot = 44, .claim_field_index = 44, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "cube_252", .enable_slot = 45, .claim_field_index = 45, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_round_keys", .enable_slot = 46, .claim_field_index = 46, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_252_width_27", .enable_slot = 47, .claim_field_index = 47, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_address_to_id", .enable_slot = 48, .claim_field_index = 48, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[0]", .enable_slot = 49, .claim_field_index = 49, .field_slot_index = 0, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[1]", .enable_slot = 50, .claim_field_index = 49, .field_slot_index = 1, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[2]", .enable_slot = 51, .claim_field_index = 49, .field_slot_index = 2, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[3]", .enable_slot = 52, .claim_field_index = 49, .field_slot_index = 3, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[4]", .enable_slot = 53, .claim_field_index = 49, .field_slot_index = 4, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[5]", .enable_slot = 54, .claim_field_index = 49, .field_slot_index = 5, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[6]", .enable_slot = 55, .claim_field_index = 49, .field_slot_index = 6, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[7]", .enable_slot = 56, .claim_field_index = 49, .field_slot_index = 7, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[8]", .enable_slot = 57, .claim_field_index = 49, .field_slot_index = 8, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[9]", .enable_slot = 58, .claim_field_index = 49, .field_slot_index = 9, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[10]", .enable_slot = 59, .claim_field_index = 49, .field_slot_index = 10, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[11]", .enable_slot = 60, .claim_field_index = 49, .field_slot_index = 11, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[12]", .enable_slot = 61, .claim_field_index = 49, .field_slot_index = 12, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[13]", .enable_slot = 62, .claim_field_index = 49, .field_slot_index = 13, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[14]", .enable_slot = 63, .claim_field_index = 49, .field_slot_index = 14, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[15]", .enable_slot = 64, .claim_field_index = 49, .field_slot_index = 15, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_small", .enable_slot = 65, .claim_field_index = 50, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_6", .enable_slot = 66, .claim_field_index = 51, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_8", .enable_slot = 67, .claim_field_index = 52, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_11", .enable_slot = 68, .claim_field_index = 53, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 11 },
    .{ .name = "range_check_12", .enable_slot = 69, .claim_field_index = 54, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 12 },
    .{ .name = "range_check_18", .enable_slot = 70, .claim_field_index = 55, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_20", .enable_slot = 71, .claim_field_index = 56, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "range_check_4_3", .enable_slot = 72, .claim_field_index = 57, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 7 },
    .{ .name = "range_check_4_4", .enable_slot = 73, .claim_field_index = 58, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_9_9", .enable_slot = 74, .claim_field_index = 59, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_7_2_5", .enable_slot = 75, .claim_field_index = 60, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "range_check_3_6_6_3", .enable_slot = 76, .claim_field_index = 61, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_4_4_4_4", .enable_slot = 77, .claim_field_index = 62, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "range_check_3_3_3_3_3", .enable_slot = 78, .claim_field_index = 63, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "verify_bitwise_xor_4", .enable_slot = 79, .claim_field_index = 64, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "verify_bitwise_xor_7", .enable_slot = 80, .claim_field_index = 65, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "verify_bitwise_xor_8", .enable_slot = 81, .claim_field_index = 66, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "verify_bitwise_xor_9", .enable_slot = 82, .claim_field_index = 67, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
};

pub const source_files = [_]SourceFile{
    .{ .path = "Cargo.toml", .sha256 = "13e791300556958768d9d54d4eac1b656a2e0eb2343122fec7ffaa36f7c77596" },
    .{ .path = "Cargo.lock", .sha256 = "9859a173771118433cfe34991cd81c33d2baf15c2267a09edb23f1f3237b7f64" },
    .{ .path = "crates/cairo-air/src/claims.rs", .sha256 = "4503336077348b7dc9c47f32a8ed4ede5fb9832a50ea57a1e220cb4dc03a00fa" },
    .{ .path = "crates/cairo-air/src/components/memory_address_to_id.rs", .sha256 = "b739dc44605df36dc827c8e71fc0f2c5d6572778db5076dfadd50188b493c929" },
    .{ .path = "crates/cairo-air/src/components/memory_id_to_big.rs", .sha256 = "da22ee9e0fe5cad238fb39a57353d2b43e9f304abd4b02dc7d809cbbd227d34c" },
    .{ .path = "crates/common/src/memory.rs", .sha256 = "856b6a4187341583ac054cffd120560deb989de7b0051a54727642de57022e3d" },
    .{ .path = "crates/common/src/preprocessed_columns/preprocessed_trace.rs", .sha256 = "42ad80419fe3ac05e8c5049a5c8562a16941fe8227eb44dd3c63e554e08c9f96" },
    .{ .path = "crates/cairo-air/src/components/blake_round_sigma.rs", .sha256 = "58ee62c618b9a694a597a1f91648507f6ff6345fc7dd0e72fd83094536768d16" },
    .{ .path = "crates/cairo-air/src/components/pedersen_points_table_window_bits_18.rs", .sha256 = "dcde0806c65716d774ba5907f453ac0054fd2ad2dafeaaf5f4886b5e105d346a" },
    .{ .path = "crates/cairo-air/src/components/pedersen_points_table_window_bits_9.rs", .sha256 = "e2639f8b7db5f9b82c4aed68f29c1c9d0c8fcc42fa3089bf77260df6f9b7a987" },
    .{ .path = "crates/cairo-air/src/components/poseidon_round_keys.rs", .sha256 = "876dd40c1abcf1fffa86823765445c7e0da36559038468066f58a4e3c67c96b3" },
    .{ .path = "crates/cairo-air/src/components/range_check_11.rs", .sha256 = "ff7fafe9a1e9ed3bc95c1249e7138dce5fdc866cdf257e576f497fb9f3f3265b" },
    .{ .path = "crates/cairo-air/src/components/range_check_12.rs", .sha256 = "4d5ed7d295ec4d8b990c1db28a44d0977d9a7246429ecb91a64548d36fc30cd1" },
    .{ .path = "crates/cairo-air/src/components/range_check_18.rs", .sha256 = "689220911c1e4a1bae6260b39ce710c4e7ae482231231b93738d65e352fd5c39" },
    .{ .path = "crates/cairo-air/src/components/range_check_20.rs", .sha256 = "b0c2ee22cdac8dbf4aaf31776b9423bf19de0b2784adf03fcf44d44f9bde3255" },
    .{ .path = "crates/cairo-air/src/components/range_check_3_3_3_3_3.rs", .sha256 = "76e2e0e11ade9e8ef684c6b1bf892855a5863a937da5ec063360cbffc459fa11" },
    .{ .path = "crates/cairo-air/src/components/range_check_3_6_6_3.rs", .sha256 = "680ea952ab1507fa8491aeca5e9bfbba7b8991068ddeeb69189e4f913ec399f0" },
    .{ .path = "crates/cairo-air/src/components/range_check_4_3.rs", .sha256 = "426ae2247c9178db6f94fd81d834f1e1221ecbeafd10c62e96b580f67036a1ac" },
    .{ .path = "crates/cairo-air/src/components/range_check_4_4.rs", .sha256 = "629d107f11996f847c0a4c5a046f7d2994910fb18222f9c238ac1622aa5b64f0" },
    .{ .path = "crates/cairo-air/src/components/range_check_4_4_4_4.rs", .sha256 = "330f8e972f96a7df60ce778d2f93179defa30865341167c6d98f51e1583cbe73" },
    .{ .path = "crates/cairo-air/src/components/range_check_6.rs", .sha256 = "959d56a8bebe1070036cc759831b67dedc157cbcade1fd8e2ddc31ebac26d433" },
    .{ .path = "crates/cairo-air/src/components/range_check_7_2_5.rs", .sha256 = "1082b91169eab9a524e1827e40d566bff8b65ce39596b28e3fe05ad379f49470" },
    .{ .path = "crates/cairo-air/src/components/range_check_8.rs", .sha256 = "527be0dcb3deb3584e5597a9fbb641111ad215a0a27aa3d889ab8e71ef2e77de" },
    .{ .path = "crates/cairo-air/src/components/range_check_9_9.rs", .sha256 = "96d3d9033c8e9f5a6f0a2193d58cd0f6eb24cf849c4454f83a421eb668088bce" },
    .{ .path = "crates/cairo-air/src/components/verify_bitwise_xor_12.rs", .sha256 = "9584ddd68860ee0527c35d2469fe5cdfa1d4126ccb2341b547c935bf7baf15ec" },
    .{ .path = "crates/cairo-air/src/components/verify_bitwise_xor_4.rs", .sha256 = "4550f17019666e7ada950b7cea09c3601d0e08067cb780950eb40eebf8668b0d" },
    .{ .path = "crates/cairo-air/src/components/verify_bitwise_xor_7.rs", .sha256 = "c54d40e0069dd3696b74094c4530c6afcba4eecc39b7d3c540777fbe22ed3ee8" },
    .{ .path = "crates/cairo-air/src/components/verify_bitwise_xor_8.rs", .sha256 = "17bee3516cc31910149c41cade09fee9eb1f73b2394eb2ce1f6573bb1172390a" },
    .{ .path = "crates/cairo-air/src/components/verify_bitwise_xor_9.rs", .sha256 = "e51fbcd0a9bdc0a341f9cf3a88f7bd513ff508d21d0272fb40af2b76ae3ac394" },
};

comptime {
    std.debug.assert(claim_fields.len == claim_field_count);
    std.debug.assert(enable_slots.len == enable_slot_count);
    var next_slot: usize = 0;
    for (claim_fields, 0..) |field, field_index| {
        std.debug.assert(field.field_index == field_index);
        std.debug.assert(field.first_enable_slot == next_slot);
        next_slot += field.enable_slot_count;
    }
    std.debug.assert(next_slot == enable_slot_count);
    for (enable_slots, 0..) |slot, slot_index| {
        std.debug.assert(slot.enable_slot == slot_index);
        const field = claim_fields[slot.claim_field_index];
        std.debug.assert(slot_index == field.first_enable_slot + slot.field_slot_index);
        std.debug.assert(slot.field_slot_index < field.enable_slot_count);
        std.debug.assert(slot.log_size_shape == field.log_size_shape);
        std.debug.assert(slot.fixed_log_size == field.fixed_log_size);
    }
}

test "claim registry cardinality and special shape" {
    try std.testing.expectEqual(@as(usize, 68), claim_fields.len);
    try std.testing.expectEqual(@as(usize, 83), enable_slots.len);
    const memory = claim_fields[49];
    try std.testing.expectEqualStrings("memory_id_to_big", memory.name);
    try std.testing.expectEqual(@as(u8, 49), memory.first_enable_slot);
    try std.testing.expectEqual(@as(u8, 16), memory.enable_slot_count);
    try std.testing.expectEqual(LogSizeShape.special_dynamic_prefix, memory.log_size_shape);
    try std.testing.expectEqual(@as(u8, 65), claim_fields[50].first_enable_slot);
}
