"""Generate the committed Zig operand-class corpus from pinned Sail runs.

Every architectural expectation in the emitted files is an output of the
pinned Sail model observed over RVFI-DII at generation time -- never a
value this repository's decoder or runner computed. There is deliberately
no fallback: if the pinned Sail binary is unavailable the generator
refuses to emit, because structurally-derived expectations presented as
Sail-derived would recreate the self-referential-oracle failure this
corpus exists to close.

pc-relative results (AUIPC, and the link register and target of JAL/JALR)
are recorded as offsets from the retiring pc, which is the form the ISA
defines them in and the only form that transfers from the generation
session's addresses to wherever a guest embeds the body.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

try:
    from riscv_sail_oracle_lib import resolution as oracle
except ModuleNotFoundError:  # Imported as scripts.riscv_operand_classes_lib.
    from scripts.riscv_sail_oracle_lib import resolution as oracle

from . import classes, encoding, session

MASK32 = 0xFFFF_FFFF
PC_RELATIVE_RD_OPS = frozenset(("auipc", "jal", "jalr"))

DEFAULT_OUTPUT_DIR = Path("src/tests/riscv/operand_class_corpus")

GENERATED_NOTE = (
    "GENERATED by `python3 scripts/riscv_operand_classes.py emit` -- do not edit."
)


@dataclasses.dataclass(frozen=True)
class EmittedCheck:
    index: int
    rd: int
    rd_value: int
    rd_pc_relative: bool
    next_pc_offset: int
    mem_addr: int
    mem_rmask: int
    mem_wmask: int
    mem_rdata: int
    mem_wdata: int


@dataclasses.dataclass(frozen=True)
class EmittedCase:
    spec: classes.CaseSpec
    rs1_val: int
    rs2_val: int
    # A pc-derived source operand (AUIPC-based JALR targets) has no
    # portable absolute value; the flag replaces the value.
    rs1_pc_derived: bool
    rs2_pc_derived: bool
    retired: tuple[int, ...]
    checks: tuple[EmittedCheck, ...]


def _check_from(ret: session.Retirement, index: int) -> EmittedCheck:
    decoded = encoding.decode(ret.insn)
    # A discarded link (rd = x0) stays absolute zero: an offset-from-pc form
    # would only reproduce zero at the generation session's own addresses.
    pc_relative = decoded["op"] in PC_RELATIVE_RD_OPS and ret.rd != 0
    rd_value = (ret.rd_value - ret.pc) & MASK32 if pc_relative else ret.rd_value
    return EmittedCheck(
        index=index,
        rd=ret.rd,
        rd_value=rd_value,
        rd_pc_relative=pc_relative,
        next_pc_offset=(ret.next_pc - ret.pc) & MASK32,
        mem_addr=ret.mem_addr,
        mem_rmask=ret.mem_rmask,
        mem_wmask=ret.mem_wmask,
        mem_rdata=ret.mem_rdata,
        mem_wdata=ret.mem_wdata,
    )


def observe_all(sail_bin: Path) -> list[EmittedCase]:
    """Run every case through pinned Sail and certify it satisfies its own
    class predicate on Sail-derived operand values."""
    cases = classes.all_cases()
    classes.validate_cases(cases)
    emitted = []
    for case in cases:
        observation = session.observe_case(sail_bin, case)
        obs = observation.under_test_obs(case)
        if not classes.PREDICATES[case.tag](obs):
            raise session.SessionError(
                f"{case.name}: Sail's observed operands do not satisfy the "
                f"claimed class {case.tag}: {obs}"
            )
        checks = [_check_from(observation.under_test(case), case.under_test)]
        if case.readback is not None:
            checks.append(_check_from(observation.by_index[case.readback], case.readback))
        reads_rs1 = case.op in classes.READS_RS1 and not observation.rs1_pc_derived
        reads_rs2 = case.op in classes.READS_RS2 and not observation.rs2_pc_derived
        emitted.append(
            EmittedCase(
                spec=case,
                rs1_val=obs.rs1 if reads_rs1 else 0,
                rs2_val=obs.rs2 if reads_rs2 else 0,
                rs1_pc_derived=observation.rs1_pc_derived,
                rs2_pc_derived=observation.rs2_pc_derived,
                retired=observation.retired,
                checks=tuple(checks),
            )
        )
    return emitted


# ---------------------------------------------------------------------------
# Zig rendering
# ---------------------------------------------------------------------------


def _header(identity: dict[str, str], group: str, count: int) -> str:
    return (
        f"//! {GENERATED_NOTE}\n"
        f"//!\n"
        f"//! Sail-derived operand-class corpus, group `{group}` ({count} cases).\n"
        f"//! Every expected value below is an output of the pinned Sail model\n"
        f"//! observed over RVFI-DII at generation time; consuming tests replay\n"
        f"//! the body and compare, they do not re-derive semantics.\n"
        f"//!\n"
        f"//! Generation authority:\n"
        f"//!   model     riscv/sail-riscv@{identity['repository_revision']}\n"
        f"//!   tag       {identity['model_tag']}, compiler {identity['compiler_version']}\n"
        f"//!   transport RVFI-DII v1, entry patch sha256 {identity['transport_patch_sha256']}\n"
        f"//! The binary hash is omitted deliberately: sail_riscv_sim builds are\n"
        f"//! not bit-reproducible, and identity is the pinned source revision\n"
        f"//! plus build-info strings, which the Sail identity contract checked\n"
        f"//! checked before a single case was observed.\n\n"
        f'const data = @import("../operand_classes.zig");\n\n'
    )


def _hex(value: int) -> str:
    return f"0x{value:08x}" if value > 9 else str(value)


def _zig_list(elements: list[str]) -> str:
    """An `&.{...}` literal in `zig fmt`'s canonical single-line shape:
    one element gets no inner padding, several get spaces -- matching the
    formatter keeps the generator's output byte-stable under it, which is
    what lets `check` compare regeneration against the committed files."""
    if len(elements) == 1:
        return "&.{" + elements[0] + "}"
    return "&.{ " + ", ".join(elements) + " }"


def _render_check(check: EmittedCheck) -> str:
    fields = [f".index = {check.index}", f".rd = {check.rd}",
              f".rd_value = {_hex(check.rd_value)}"]
    if check.rd_pc_relative:
        fields.append(".rd_pc_relative = true")
    if check.next_pc_offset != 4:
        fields.append(f".next_pc_offset = {_hex(check.next_pc_offset)}")
    if check.mem_rmask or check.mem_wmask:
        fields.append(f".mem_addr = {_hex(check.mem_addr)}")
        fields.append(f".mem_rmask = {check.mem_rmask}")
        fields.append(f".mem_wmask = {check.mem_wmask}")
        fields.append(f".mem_rdata = {_hex(check.mem_rdata)}")
        fields.append(f".mem_wdata = {_hex(check.mem_wdata)}")
    return ".{ " + ", ".join(fields) + " }"


def _render_case(case: EmittedCase) -> str:
    spec = case.spec
    fields = [
        f'.name = "{spec.name}"',
        f".op = .{spec.op.upper()}",
        f".class = .{spec.tag}",
    ]
    if case.rs1_val:
        fields.append(f".rs1_val = {_hex(case.rs1_val)}")
    if case.rs2_val:
        fields.append(f".rs2_val = {_hex(case.rs2_val)}")
    if case.rs1_pc_derived:
        fields.append(".rs1_pc_derived = true")
    if case.rs2_pc_derived:
        fields.append(".rs2_pc_derived = true")
    fields.append(".body = " + _zig_list([f"0x{word:08x}" for word in spec.body]))
    fields.append(f".under_test = {spec.under_test}")
    fields.append(".retired = " + _zig_list([str(index) for index in case.retired]))
    fields.append(".checks = " + _zig_list([_render_check(c) for c in case.checks]))
    return "    .{ " + ", ".join(fields) + " },"


def render_group(identity: dict[str, str], group: str, cases: list[EmittedCase]) -> str:
    lines = [_header(identity, group, len(cases))]
    lines.append("pub const cases = [_]data.Case{\n")
    for case in cases:
        lines.append(_render_case(case) + "\n")
    lines.append("};\n")
    return "".join(lines)


def render_tags(identity: dict[str, str]) -> str:
    """The Class enum, generated from the predicate table so the tag list
    has exactly one owner; a corpus tag the enum lacks is a compile error."""
    tags = "\n".join(f"    {tag}," for tag in classes.PREDICATES)
    return (
        f"//! {GENERATED_NOTE}\n"
        f"//!\n"
        f"//! Operand-class tags, one per predicate in\n"
        f"//! `scripts/riscv_operand_classes_lib/classes.py`, which owns their\n"
        f"//! definitions. Generated with the corpus (model tag\n"
        f"//! {identity['model_tag']}) so tag list and data cannot drift apart\n"
        f"//! without a compile error.\n\n"
        f"pub const Class = enum {{\n{tags}\n}};\n"
    )


def group_of(op_name: str) -> str:
    for group, ops in classes.GROUPS.items():
        if op_name in ops:
            return group
    raise ValueError(f"opcode {op_name} belongs to no output group")


def emit(sail_bin: Path, identity: dict[str, str], output_dir: Path) -> dict[str, int]:
    """Observe every case and write the corpus files. Returns per-file case
    counts so the caller can report what was written."""
    emitted = observe_all(sail_bin)
    grouped: dict[str, list[EmittedCase]] = {name: [] for name in classes.GROUPS}
    for case in emitted:
        grouped[group_of(case.spec.op)].append(case)
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "tags.zig").write_text(render_tags(identity), encoding="utf-8")
    counts = {}
    for group, cases in grouped.items():
        path = output_dir / f"{group}.zig"
        path.write_text(render_group(identity, group, cases), encoding="utf-8")
        counts[group] = len(cases)
    return counts


def resolve() -> tuple[Path, dict[str, str]]:
    """The pinned binary and its verified identity, or SailUnavailable."""
    resolved = oracle.resolve_sail()
    return resolved.binary, resolved.identity
