//! CP-11 relation evidence over retained production commitment inputs.
//!
//! `RetainedTree` is a byte-for-byte snapshot taken immediately before the
//! proving engine consumes Tree 0 or Tree 1. Evidence is derived only from
//! those snapshots and from native interaction claims generated by the normal
//! AIR interaction builders under the pinned diagnostic challenges.

const std = @import("std");
const M31 = @import("../../../core/fields/m31.zig").M31;
const prover_pcs = @import("../../../prover/pcs/mod.zig");
const component_order = @import("../air/component_order.zig");
const poseidon2_air = @import("../air/memory_commitment/poseidon2_air.zig");
const relation_evidence = @import("../air/relation_evidence.zig");
const relation_export = @import("../air/relation_export.zig");
const relation_components = @import("../air/relation_export_components.zig");
const relations_mod = @import("../air/relation_challenges.zig");
const statement_mod = @import("../air/statement.zig");
const trace = @import("../runner/trace.zig");
const witness_layout = @import("../witness_layout.zig");

pub const Error = error{
    InvalidTreeShape,
    InvalidComponentPlacement,
    MissingInfrastructureComponent,
    DuplicateInfrastructureComponent,
};

pub const RetainedTree = struct {
    columns: []prover_pcs.ColumnEvaluation,

    pub fn capture(
        allocator: std.mem.Allocator,
        columns: []const prover_pcs.ColumnEvaluation,
    ) !RetainedTree {
        const retained = try allocator.alloc(prover_pcs.ColumnEvaluation, columns.len);
        var initialized: usize = 0;
        errdefer {
            for (retained[0..initialized]) |column| allocator.free(@constCast(column.values));
            allocator.free(retained);
        }
        for (columns, retained) |source, *destination| {
            destination.* = .{
                .log_size = source.log_size,
                .values = try allocator.dupe(M31, source.values),
            };
            initialized += 1;
        }
        return .{ .columns = retained };
    }

    pub fn deinit(self: *RetainedTree, allocator: std.mem.Allocator) void {
        for (self.columns) |column| allocator.free(@constCast(column.values));
        allocator.free(self.columns);
        self.* = undefined;
    }
};

pub const Output = struct {
    bundle: relation_evidence.Bundle,
    relations: relations_mod.Relations,
};

pub fn build(
    allocator: std.mem.Allocator,
    statement: *const statement_mod.RiscVStatement,
    tree0: *const RetainedTree,
    tree1: *const RetainedTree,
    roots: [3]relation_export.Digest,
    relations: relations_mod.Relations,
    interaction_claim: *const statement_mod.RiscVInteractionClaim,
) !Output {
    try validateTreeShapes(statement, tree0, tree1);
    const canonical = try interaction_claim.canonical(statement);
    const native = canonical.view();
    var ledger = try relation_export.ClaimLedger.init(
        roots[0],
        roots[1],
        roots[2],
        &native,
    );
    var sequence = try relation_export.Sequence.initForExecution(allocator, statement.total_steps);
    defer sequence.deinit(allocator);
    var observer = relation_export.NullObserver{};
    var evidence: [relation_export.COMPONENT_COUNT]relation_export.ComponentEvidence = undefined;

    const opcode_offsets = opcodeMainOffsets(statement);
    for (component_order.OPCODE_FAMILIES) |family| {
        const component = component_order.transcriptComponentForOpcodeFamily(family);
        var shards: [statement_mod.MAX_COMPONENTS]relation_export.OpcodeShard = undefined;
        var views: [statement_mod.MAX_COMPONENTS][trace.MAX_FAMILY_COLUMNS][]const M31 = undefined;
        var count: usize = 0;
        for (0..statement.n_components) |index| {
            const desc = statement.component_descs[index];
            if (desc.family != family) continue;
            const offset = opcode_offsets[index];
            for (views[count][0..desc.n_columns], 0..) |*view, column| {
                view.* = tree1.columns[offset + column].values;
            }
            shards[count] = .{
                .ordinal = @intCast(count),
                .shard_count = 0,
                .n_real_rows = desc.n_rows,
                .committed_columns = views[count][0..desc.n_columns],
                .main_columns_digest = undefined,
            };
            count += 1;
        }
        if (count == 0) {
            evidence[@intFromEnum(component)] = try relation_export.exportAbsentComponent(
                component,
                &ledger,
                &sequence,
            );
            continue;
        }
        for (shards[0..count]) |*shard| {
            shard.shard_count = @intCast(count);
            shard.main_columns_digest = relation_export.digestCommittedShard(
                component,
                family,
                shard.*,
            );
        }
        evidence[@intFromEnum(component)] = try relation_export.exportOpcodeFamily(
            allocator,
            family,
            shards[0..count],
            &relations,
            &ledger,
            &sequence,
            &observer,
        );
    }

    const infra_offsets = infrastructureMainOffsets(statement);
    for ([_]statement_mod.InfraKind{
        statement_mod.InfraKind.program,
        statement_mod.InfraKind.memory,
        statement_mod.InfraKind.merkle,
        statement_mod.InfraKind.poseidon2,
        statement_mod.InfraKind.clock_update,
    }) |kind| {
        const component = componentForInfrastructure(kind);
        var shards: [statement_mod.MAX_INFRA_COMPONENTS]relation_components.CommittedShard = undefined;
        var views: [statement_mod.MAX_INFRA_COMPONENTS][poseidon2_air.N_MAIN_COLUMNS][]const M31 = undefined;
        var count: usize = 0;
        for (0..statement.n_infra) |index| {
            const desc = statement.infra_descs[index];
            if (desc.kind != kind) continue;
            const offset = infra_offsets[index];
            for (views[count][0..desc.n_columns], 0..) |*view, column| {
                view.* = tree1.columns[offset + column].values;
            }
            const selector = tree0.columns[statement.preprocessedOffsetForInfra(index) + 1].values;
            shards[count] = .{
                .ordinal = @intCast(count),
                .shard_count = 0,
                .n_real_rows = desc.n_rows,
                .committed_columns = views[count][0..desc.n_columns],
                .main_columns_digest = undefined,
                .selector_column = selector,
                .selector_digest = undefined,
            };
            count += 1;
        }
        if (count == 0) {
            evidence[@intFromEnum(component)] = try relation_export.exportAbsentComponent(
                component,
                &ledger,
                &sequence,
            );
            continue;
        }
        for (shards[0..count]) |*shard| {
            shard.shard_count = @intCast(count);
            shard.main_columns_digest = relation_components.digestCommittedShard(component, shard.*);
            shard.selector_digest = relation_components.digestSelector(component, shard.*).?;
        }
        evidence[@intFromEnum(component)] = try relation_components.exportInfrastructure(
            allocator,
            infrastructureExportKind(kind),
            shards[0..count],
            &relations,
            &ledger,
            &sequence,
            &observer,
        );
    }

    for (component_order.LOOKUP_TABLES) |kind| {
        const component = component_order.transcriptComponentForLookupTable(kind);
        const infra_index = try uniqueInfrastructureIndex(
            statement,
            statement_mod.infraKindForTable(kind),
        );
        const preprocessed_offset = statement.preprocessedOffsetForInfra(infra_index);
        var tuple_views: [@import("../air/lookups/tables/schema.zig").MAX_ARITY][]const M31 = undefined;
        for (tuple_views[0..@import("../air/lookups/tables/schema.zig").arity(kind)], 0..) |*view, column| {
            view.* = tree0.columns[preprocessed_offset + 1 + column].values;
        }
        var source = relation_components.LookupTableSource{
            .kind = kind,
            .multiplicity_column = tree1.columns[infra_offsets[infra_index]].values,
            .tuple_columns = tuple_views[0..@import("../air/lookups/tables/schema.zig").arity(kind)],
            .main_columns_digest = undefined,
            .preprocessed_columns_digest = undefined,
        };
        source.main_columns_digest = relation_components.digestLookupMain(source);
        source.preprocessed_columns_digest = relation_components.digestLookupPreprocessed(source);
        evidence[@intFromEnum(component)] = try relation_components.exportLookupTable(
            allocator,
            source,
            &relations,
            &ledger,
            &sequence,
            &observer,
        );
    }

    return .{
        .bundle = .{
            .witness_layout_digest = witness_layout.digest(),
            .components = evidence,
            .aggregate = try sequence.finish(),
            .claims = try ledger.finish(),
            .public = try relation_export.publicEvidence(&statement.public_data, &relations),
        },
        .relations = relations,
    };
}

fn validateTreeShapes(
    statement: *const statement_mod.RiscVStatement,
    tree0: *const RetainedTree,
    tree1: *const RetainedTree,
) Error!void {
    if (tree0.columns.len != statement.nPreprocessedColumns() or
        tree1.columns.len != statement.nMainColumns()) return error.InvalidTreeShape;
    for (tree0.columns) |column| column.validate() catch return error.InvalidTreeShape;
    for (tree1.columns) |column| column.validate() catch return error.InvalidTreeShape;
}

fn opcodeMainOffsets(statement: *const statement_mod.RiscVStatement) [statement_mod.MAX_COMPONENTS]usize {
    var result: [statement_mod.MAX_COMPONENTS]usize = undefined;
    var offset: usize = 0;
    for (0..statement.n_components) |index| {
        result[index] = offset;
        offset += statement.component_descs[index].n_columns;
    }
    return result;
}

fn infrastructureMainOffsets(statement: *const statement_mod.RiscVStatement) [statement_mod.MAX_INFRA_COMPONENTS]usize {
    var result: [statement_mod.MAX_INFRA_COMPONENTS]usize = undefined;
    var offset: usize = statement.nOpcodeMainColumns();
    for (0..statement.n_infra) |index| {
        result[index] = offset;
        offset += statement.infra_descs[index].n_columns;
    }
    return result;
}

fn uniqueInfrastructureIndex(
    statement: *const statement_mod.RiscVStatement,
    kind: statement_mod.InfraKind,
) Error!usize {
    var result: ?usize = null;
    for (0..statement.n_infra) |index| {
        if (statement.infra_descs[index].kind != kind) continue;
        if (result != null) return error.DuplicateInfrastructureComponent;
        result = index;
    }
    return result orelse error.MissingInfrastructureComponent;
}

fn componentForInfrastructure(kind: statement_mod.InfraKind) relation_export.Component {
    return switch (kind) {
        .program => .program,
        .memory => .memory,
        .merkle => .merkle,
        .poseidon2 => .poseidon2,
        .clock_update => .clock_update,
        else => unreachable,
    };
}

fn infrastructureExportKind(kind: statement_mod.InfraKind) relation_components.InfrastructureKind {
    return switch (kind) {
        .program => .program,
        .memory => .memory,
        .merkle => .merkle,
        .poseidon2 => .poseidon2,
        .clock_update => .clock_update,
        else => unreachable,
    };
}
