//! Version-pinned Cairo claim registry.
//!
//! Generated by `scripts/generate_cairo_claim_registry.py`; do not edit by hand.

const std = @import("std");

pub const SourceRevision = struct {
    stwo_cairo: []const u8,
    stwo: []const u8,
};

pub const SourceFile = struct {
    path: []const u8,
    sha256: []const u8,
};

pub const LogSizeShape = enum {
    dynamic,
    fixed,
    special_dynamic_prefix,
};

pub const ClaimField = struct {
    name: []const u8,
    field_index: u8,
    first_enable_slot: u8,
    enable_slot_count: u8,
    log_size_shape: LogSizeShape,
    fixed_log_size: ?u32,
};

pub const EnableSlot = struct {
    name: []const u8,
    enable_slot: u8,
    claim_field_index: u8,
    field_slot_index: u8,
    log_size_shape: LogSizeShape,
    fixed_log_size: ?u32,
};

pub const source_revision = SourceRevision{
    .stwo_cairo = "dcd5834565b7a26a27a614e353c9c60109ebc1d9",
    .stwo = "9d7e3d6fa0fc64a0d143a8b2fcb8ee952f4de8f2",
};
pub const registry_sha256 = "167b18e623e0905e5102fc9dce7ac9406891bafb7289577e93476ce617bd1c8e";
pub const claim_field_count: usize = 68;
pub const enable_slot_count: usize = 83;
pub const memory_id_to_big_enable_slot_count: usize = 16;

pub const claim_fields = [_]ClaimField{
    .{ .name = "add_opcode", .field_index = 0, .first_enable_slot = 0, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_opcode_small", .field_index = 1, .first_enable_slot = 1, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_ap_opcode", .field_index = 2, .first_enable_slot = 2, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode", .field_index = 3, .first_enable_slot = 3, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_imm", .field_index = 4, .first_enable_slot = 4, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_double_deref", .field_index = 5, .first_enable_slot = 5, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_compress_opcode", .field_index = 6, .first_enable_slot = 6, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_abs", .field_index = 7, .first_enable_slot = 7, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_rel_imm", .field_index = 8, .first_enable_slot = 8, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "generic_opcode", .field_index = 9, .first_enable_slot = 9, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_non_taken", .field_index = 10, .first_enable_slot = 10, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_taken", .field_index = 11, .first_enable_slot = 11, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_abs", .field_index = 12, .first_enable_slot = 12, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_double_deref", .field_index = 13, .first_enable_slot = 13, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel", .field_index = 14, .first_enable_slot = 14, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel_imm", .field_index = 15, .first_enable_slot = 15, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode", .field_index = 16, .first_enable_slot = 16, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode_small", .field_index = 17, .first_enable_slot = 17, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "qm_31_add_mul_opcode", .field_index = 18, .first_enable_slot = 18, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ret_opcode", .field_index = 19, .first_enable_slot = 19, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_instruction", .field_index = 20, .first_enable_slot = 20, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round", .field_index = 21, .first_enable_slot = 21, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_g", .field_index = 22, .first_enable_slot = 22, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round_sigma", .field_index = 23, .first_enable_slot = 23, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 4 },
    .{ .name = "triple_xor_32", .field_index = 24, .first_enable_slot = 24, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_bitwise_xor_12", .field_index = 25, .first_enable_slot = 25, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "add_mod_builtin", .field_index = 26, .first_enable_slot = 26, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "bitwise_builtin", .field_index = 27, .first_enable_slot = 27, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_mod_builtin", .field_index = 28, .first_enable_slot = 28, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin", .field_index = 29, .first_enable_slot = 29, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin_narrow_windows", .field_index = 30, .first_enable_slot = 30, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_builtin", .field_index = 31, .first_enable_slot = 31, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check96_builtin", .field_index = 32, .first_enable_slot = 32, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_builtin", .field_index = 33, .first_enable_slot = 33, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ec_op_builtin", .field_index = 34, .first_enable_slot = 34, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_generic", .field_index = 35, .first_enable_slot = 35, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_aggregator_window_bits_18", .field_index = 36, .first_enable_slot = 36, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_18", .field_index = 37, .first_enable_slot = 37, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_18", .field_index = 38, .first_enable_slot = 38, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 23 },
    .{ .name = "pedersen_aggregator_window_bits_9", .field_index = 39, .first_enable_slot = 39, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_9", .field_index = 40, .first_enable_slot = 40, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_9", .field_index = 41, .first_enable_slot = 41, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "poseidon_aggregator", .field_index = 42, .first_enable_slot = 42, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_3_partial_rounds_chain", .field_index = 43, .first_enable_slot = 43, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_full_round_chain", .field_index = 44, .first_enable_slot = 44, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "cube_252", .field_index = 45, .first_enable_slot = 45, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_round_keys", .field_index = 46, .first_enable_slot = 46, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_252_width_27", .field_index = 47, .first_enable_slot = 47, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_address_to_id", .field_index = 48, .first_enable_slot = 48, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_id_to_big", .field_index = 49, .first_enable_slot = 49, .enable_slot_count = 16, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_small", .field_index = 50, .first_enable_slot = 65, .enable_slot_count = 1, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_6", .field_index = 51, .first_enable_slot = 66, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_8", .field_index = 52, .first_enable_slot = 67, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_11", .field_index = 53, .first_enable_slot = 68, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 11 },
    .{ .name = "range_check_12", .field_index = 54, .first_enable_slot = 69, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 12 },
    .{ .name = "range_check_18", .field_index = 55, .first_enable_slot = 70, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_20", .field_index = 56, .first_enable_slot = 71, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "range_check_4_3", .field_index = 57, .first_enable_slot = 72, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 7 },
    .{ .name = "range_check_4_4", .field_index = 58, .first_enable_slot = 73, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_9_9", .field_index = 59, .first_enable_slot = 74, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_7_2_5", .field_index = 60, .first_enable_slot = 75, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "range_check_3_6_6_3", .field_index = 61, .first_enable_slot = 76, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_4_4_4_4", .field_index = 62, .first_enable_slot = 77, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "range_check_3_3_3_3_3", .field_index = 63, .first_enable_slot = 78, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "verify_bitwise_xor_4", .field_index = 64, .first_enable_slot = 79, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "verify_bitwise_xor_7", .field_index = 65, .first_enable_slot = 80, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "verify_bitwise_xor_8", .field_index = 66, .first_enable_slot = 81, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "verify_bitwise_xor_9", .field_index = 67, .first_enable_slot = 82, .enable_slot_count = 1, .log_size_shape = .fixed, .fixed_log_size = 18 },
};

pub const enable_slots = [_]EnableSlot{
    .{ .name = "add_opcode", .enable_slot = 0, .claim_field_index = 0, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_opcode_small", .enable_slot = 1, .claim_field_index = 1, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "add_ap_opcode", .enable_slot = 2, .claim_field_index = 2, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode", .enable_slot = 3, .claim_field_index = 3, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_imm", .enable_slot = 4, .claim_field_index = 4, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "assert_eq_opcode_double_deref", .enable_slot = 5, .claim_field_index = 5, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_compress_opcode", .enable_slot = 6, .claim_field_index = 6, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_abs", .enable_slot = 7, .claim_field_index = 7, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "call_opcode_rel_imm", .enable_slot = 8, .claim_field_index = 8, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "generic_opcode", .enable_slot = 9, .claim_field_index = 9, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_non_taken", .enable_slot = 10, .claim_field_index = 10, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jnz_opcode_taken", .enable_slot = 11, .claim_field_index = 11, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_abs", .enable_slot = 12, .claim_field_index = 12, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_double_deref", .enable_slot = 13, .claim_field_index = 13, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel", .enable_slot = 14, .claim_field_index = 14, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "jump_opcode_rel_imm", .enable_slot = 15, .claim_field_index = 15, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode", .enable_slot = 16, .claim_field_index = 16, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_opcode_small", .enable_slot = 17, .claim_field_index = 17, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "qm_31_add_mul_opcode", .enable_slot = 18, .claim_field_index = 18, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ret_opcode", .enable_slot = 19, .claim_field_index = 19, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_instruction", .enable_slot = 20, .claim_field_index = 20, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round", .enable_slot = 21, .claim_field_index = 21, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_g", .enable_slot = 22, .claim_field_index = 22, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "blake_round_sigma", .enable_slot = 23, .claim_field_index = 23, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 4 },
    .{ .name = "triple_xor_32", .enable_slot = 24, .claim_field_index = 24, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "verify_bitwise_xor_12", .enable_slot = 25, .claim_field_index = 25, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "add_mod_builtin", .enable_slot = 26, .claim_field_index = 26, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "bitwise_builtin", .enable_slot = 27, .claim_field_index = 27, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "mul_mod_builtin", .enable_slot = 28, .claim_field_index = 28, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin", .enable_slot = 29, .claim_field_index = 29, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_builtin_narrow_windows", .enable_slot = 30, .claim_field_index = 30, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_builtin", .enable_slot = 31, .claim_field_index = 31, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check96_builtin", .enable_slot = 32, .claim_field_index = 32, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_builtin", .enable_slot = 33, .claim_field_index = 33, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "ec_op_builtin", .enable_slot = 34, .claim_field_index = 34, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_generic", .enable_slot = 35, .claim_field_index = 35, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_aggregator_window_bits_18", .enable_slot = 36, .claim_field_index = 36, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_18", .enable_slot = 37, .claim_field_index = 37, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_18", .enable_slot = 38, .claim_field_index = 38, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 23 },
    .{ .name = "pedersen_aggregator_window_bits_9", .enable_slot = 39, .claim_field_index = 39, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "partial_ec_mul_window_bits_9", .enable_slot = 40, .claim_field_index = 40, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "pedersen_points_table_window_bits_9", .enable_slot = 41, .claim_field_index = 41, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "poseidon_aggregator", .enable_slot = 42, .claim_field_index = 42, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_3_partial_rounds_chain", .enable_slot = 43, .claim_field_index = 43, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_full_round_chain", .enable_slot = 44, .claim_field_index = 44, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "cube_252", .enable_slot = 45, .claim_field_index = 45, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "poseidon_round_keys", .enable_slot = 46, .claim_field_index = 46, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_252_width_27", .enable_slot = 47, .claim_field_index = 47, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_address_to_id", .enable_slot = 48, .claim_field_index = 48, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[0]", .enable_slot = 49, .claim_field_index = 49, .field_slot_index = 0, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[1]", .enable_slot = 50, .claim_field_index = 49, .field_slot_index = 1, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[2]", .enable_slot = 51, .claim_field_index = 49, .field_slot_index = 2, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[3]", .enable_slot = 52, .claim_field_index = 49, .field_slot_index = 3, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[4]", .enable_slot = 53, .claim_field_index = 49, .field_slot_index = 4, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[5]", .enable_slot = 54, .claim_field_index = 49, .field_slot_index = 5, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[6]", .enable_slot = 55, .claim_field_index = 49, .field_slot_index = 6, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[7]", .enable_slot = 56, .claim_field_index = 49, .field_slot_index = 7, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[8]", .enable_slot = 57, .claim_field_index = 49, .field_slot_index = 8, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[9]", .enable_slot = 58, .claim_field_index = 49, .field_slot_index = 9, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[10]", .enable_slot = 59, .claim_field_index = 49, .field_slot_index = 10, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[11]", .enable_slot = 60, .claim_field_index = 49, .field_slot_index = 11, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[12]", .enable_slot = 61, .claim_field_index = 49, .field_slot_index = 12, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[13]", .enable_slot = 62, .claim_field_index = 49, .field_slot_index = 13, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[14]", .enable_slot = 63, .claim_field_index = 49, .field_slot_index = 14, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_big[15]", .enable_slot = 64, .claim_field_index = 49, .field_slot_index = 15, .log_size_shape = .special_dynamic_prefix, .fixed_log_size = null },
    .{ .name = "memory_id_to_small", .enable_slot = 65, .claim_field_index = 50, .field_slot_index = 0, .log_size_shape = .dynamic, .fixed_log_size = null },
    .{ .name = "range_check_6", .enable_slot = 66, .claim_field_index = 51, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 6 },
    .{ .name = "range_check_8", .enable_slot = 67, .claim_field_index = 52, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_11", .enable_slot = 68, .claim_field_index = 53, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 11 },
    .{ .name = "range_check_12", .enable_slot = 69, .claim_field_index = 54, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 12 },
    .{ .name = "range_check_18", .enable_slot = 70, .claim_field_index = 55, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_20", .enable_slot = 71, .claim_field_index = 56, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 20 },
    .{ .name = "range_check_4_3", .enable_slot = 72, .claim_field_index = 57, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 7 },
    .{ .name = "range_check_4_4", .enable_slot = 73, .claim_field_index = 58, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "range_check_9_9", .enable_slot = 74, .claim_field_index = 59, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_7_2_5", .enable_slot = 75, .claim_field_index = 60, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "range_check_3_6_6_3", .enable_slot = 76, .claim_field_index = 61, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
    .{ .name = "range_check_4_4_4_4", .enable_slot = 77, .claim_field_index = 62, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "range_check_3_3_3_3_3", .enable_slot = 78, .claim_field_index = 63, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 15 },
    .{ .name = "verify_bitwise_xor_4", .enable_slot = 79, .claim_field_index = 64, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 8 },
    .{ .name = "verify_bitwise_xor_7", .enable_slot = 80, .claim_field_index = 65, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 14 },
    .{ .name = "verify_bitwise_xor_8", .enable_slot = 81, .claim_field_index = 66, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 16 },
    .{ .name = "verify_bitwise_xor_9", .enable_slot = 82, .claim_field_index = 67, .field_slot_index = 0, .log_size_shape = .fixed, .fixed_log_size = 18 },
};

pub const source_files = [_]SourceFile{
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/claims.rs", .sha256 = "3b9e057ea948216adee9be79cfa5cb7c248a58d087464d2a8b3df149ea89c049" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/memory_address_to_id.rs", .sha256 = "be5bb1313aa90db1332fdc18141974830fa0863330c64ddfeec8ebd808ebfef5" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/memory_id_to_big.rs", .sha256 = "e8b922cbb19543804b7726704fede3d3bfc6fbf318ac9bb5c141f318fb0e131b" },
    .{ .path = "stwo_cairo_prover/crates/common/src/memory.rs", .sha256 = "856b6a4187341583ac054cffd120560deb989de7b0051a54727642de57022e3d" },
    .{ .path = "stwo_cairo_prover/crates/common/src/preprocessed_columns/preprocessed_trace.rs", .sha256 = "56864309c178d5ef28beb0e75940bc3a67ee8be16f04ec11c0f8b8575376b9e7" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/blake_round_sigma.rs", .sha256 = "34562d0f93841fc66049ad11504e9255062cb8e7900ad3dc1327001f1025df5f" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/pedersen_points_table_window_bits_18.rs", .sha256 = "da57227441b3ddc39ca5537c1ff99ae62f27b272a17b0e423ee475912e2c7f12" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/pedersen_points_table_window_bits_9.rs", .sha256 = "1d6f3f8ca4b786c6ddb2b4049eb2cfad6116adff195bb12ebd5813c326fa51ca" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/poseidon_round_keys.rs", .sha256 = "6c3048ab79147dbed12760fb6e4920826b021d46ede043dcc5eff2f1fc327f09" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_11.rs", .sha256 = "5e5a873bd7c6523032ad6e13e6d1959d2773101b11818134f193b5a13a4c5117" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_12.rs", .sha256 = "6dd53bfc5a5a114c4debdc22ba9d3723fee8257eda3a851788b8e65d54bd4315" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_18.rs", .sha256 = "a74c7ef608662110d696c5dcf333a45ef6cfdf8cb6b4906b440476d92683a5a1" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_20.rs", .sha256 = "8d37d095918fb70cbf0bb3d42b8aab98248c08cc8cd72964757bd19039a8b13f" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_3_3_3_3_3.rs", .sha256 = "b5dd2175da4c0c6695113cecd891600182ec538cddbda3d52219ca97256eb5a6" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_3_6_6_3.rs", .sha256 = "2ba755f93d9053777ef4b49ca83c8daa15f3197c14d6ac81cb363058337d9b85" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_4_3.rs", .sha256 = "97887d9d0acc6f9dd842e643e7e8e59e9a1060c043d006a93fe978641a778e91" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_4_4.rs", .sha256 = "b2b7672c3afbbbdcdd2a165576b144e5c3f0cad7c572ccf4745c429bdd10e1f5" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_4_4_4_4.rs", .sha256 = "b2d759c7ca81d9088cd142bf756a00af672e023a06afcf9dd8edff09585413d7" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_6.rs", .sha256 = "b8e6ef59cf809a3ebeb463b1573003810abb58eaa6a07a3423f7ffaad76234ef" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_7_2_5.rs", .sha256 = "4b9e0866fcfd8187c9fed745a456a819a684213df2edcea309862359b088a0ba" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_8.rs", .sha256 = "dbdfc5f340972ade097f2a118ec2c45c6df445c63c0e35c2cb929789195168be" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/range_check_9_9.rs", .sha256 = "b4f86040518b80cf4618757545cdba34963b687ea59806a0c07e730b04aba30d" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/verify_bitwise_xor_12.rs", .sha256 = "bd4ecc9d4538235364f3157d220df0632e7289e720880c4913faf9d257c03853" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/verify_bitwise_xor_4.rs", .sha256 = "2ec1fca632e4fddc90b375ac312242e7cc6eba7e53d62a56c0d6399188a138ae" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/verify_bitwise_xor_7.rs", .sha256 = "caea8b2929a9fddd57dd1254fa259bf19cb40859ba26e878fc5b0cfb142443e2" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/verify_bitwise_xor_8.rs", .sha256 = "9db10efabf6561e6a6dedb60cbd93c3ff5c3f85a7f38a7bd10075bbe8147c3dd" },
    .{ .path = "stwo_cairo_prover/crates/cairo-air/src/components/verify_bitwise_xor_9.rs", .sha256 = "c878573059d165f3f37d3e922ef3915118c29035400f886fe185bda78787aeac" },
};

comptime {
    std.debug.assert(claim_fields.len == claim_field_count);
    std.debug.assert(enable_slots.len == enable_slot_count);
    var next_slot: usize = 0;
    for (claim_fields, 0..) |field, field_index| {
        std.debug.assert(field.field_index == field_index);
        std.debug.assert(field.first_enable_slot == next_slot);
        next_slot += field.enable_slot_count;
    }
    std.debug.assert(next_slot == enable_slot_count);
    for (enable_slots, 0..) |slot, slot_index| {
        std.debug.assert(slot.enable_slot == slot_index);
        const field = claim_fields[slot.claim_field_index];
        std.debug.assert(slot_index == field.first_enable_slot + slot.field_slot_index);
        std.debug.assert(slot.field_slot_index < field.enable_slot_count);
        std.debug.assert(slot.log_size_shape == field.log_size_shape);
        std.debug.assert(slot.fixed_log_size == field.fixed_log_size);
    }
}

test "claim registry cardinality and special shape" {
    try std.testing.expectEqual(@as(usize, 68), claim_fields.len);
    try std.testing.expectEqual(@as(usize, 83), enable_slots.len);
    const memory = claim_fields[49];
    try std.testing.expectEqualStrings("memory_id_to_big", memory.name);
    try std.testing.expectEqual(@as(u8, 49), memory.first_enable_slot);
    try std.testing.expectEqual(@as(u8, 16), memory.enable_slot_count);
    try std.testing.expectEqual(LogSizeShape.special_dynamic_prefix, memory.log_size_shape);
    try std.testing.expectEqual(@as(u8, 65), claim_fields[50].first_enable_slot);
}
