[package]
name = "stwo-cairo-air-compiler"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[package.metadata.source-authority]
stwo-cairo-repository = "https://github.com/starkware-libs/stwo-cairo"
stwo-cairo-revision = "82f21252a68ec006d73e299f5bf1ce6d4db0ee78"
official-stwo-repository = "https://github.com/starkware-libs/stwo"
official-stwo-revision = "7b211edde786775016ef3eecb837a6240d8fe792"

[dependencies]
anyhow = "1.0"
cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "82f21252a68ec006d73e299f5bf1ce6d4db0ee78" }
num-traits = "0.2"
serde_json = "1.0"
stwo = { path = "../../target/cairo-air-official-stwo/crates/stwo" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "82f21252a68ec006d73e299f5bf1ce6d4db0ee78" }
stwo-cairo-common = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "82f21252a68ec006d73e299f5bf1ce6d4db0ee78" }
stwo-cairo-prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "82f21252a68ec006d73e299f5bf1ce6d4db0ee78" }
stwo-constraint-framework = { path = "../../target/cairo-air-official-stwo/crates/constraint-framework", features = ["prover"] }

[patch."https://github.com/starkware-libs/stwo"]
stwo = { path = "../../target/cairo-air-official-stwo/crates/stwo" }
stwo-constraint-framework = { path = "../../target/cairo-air-official-stwo/crates/constraint-framework" }

[workspace]
