#!/usr/bin/env python3
"""Canonical direct Zig commands for the named Stwo protocol module graph."""

from __future__ import annotations

from pathlib import Path


def protocol_module_args(root_source: str) -> list[str]:
    return [
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_metal_backend",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_riscv_frontend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_riscv_cpu_integration",
        "--dep",
        "stwo_cairo_cpu_integration",
        "--dep",
        "stwo_cairo_metal_integration",
        "--dep",
        "stwo_metal_session",
        "--dep",
        "stwo_proof_wire",
        "--dep",
        "stwo_native_examples",
        "--dep",
        "stwo_native_cuda_integration",
        "--dep",
        "stwo_cairo_cuda_integration",
        f"-Mroot={root_source}",
        "-Mstwo_core=src/core/mod.zig",
        "--dep",
        "stwo_core",
        "-Mstwo_proof_wire=src/interop/proof_wire/mod.zig",
        "--dep",
        "stwo_core",
        "-Mstwo_backend_contracts=src/backend/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "-Mstwo_prover_impl=src/prover/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cpu_backend=src/backends/cpu_scalar/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_proof_wire",
        "-Mstwo_native_examples=src/examples/mod.zig",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_native_examples",
        "--dep",
        "stwo_proof_wire",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_native_cuda_integration=src/integrations/native_cuda/mod.zig",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_native_cuda_integration",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cairo_cuda_integration=src/integrations/cairo_cuda/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "-Mstwo_metal_backend=src/backends/metal/mod.zig",
        "--dep",
        "stwo_backend_contracts",
        "-Mstwo_cuda_backend=src/backends/cuda/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_riscv_frontend=src/frontends/riscv/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cairo_frontend=src/frontends/cairo/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_riscv_frontend",
        "-Mstwo_riscv_cpu_integration=src/integrations/riscv_cpu/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_cairo_frontend",
        "-Mstwo_cairo_cpu_integration=src/integrations/cairo_cpu/mod.zig",
        "-Mstwo_metal_session=src/tools/metal_session/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_metal_backend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_metal_session",
        "-Mstwo_cairo_metal_integration=src/integrations/cairo_metal/mod.zig",
    ]


def test_command(root_source: str, *arguments: str) -> list[str]:
    return ["zig", "test", *protocol_module_args(root_source), *arguments]


def aggregate_run_command(root_source: str, *arguments: str) -> list[str]:
    return [
        "zig",
        "run",
        "-lc",
        "--dep",
        "stwo",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_metal_backend",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_riscv_frontend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_riscv_cpu_integration",
        "--dep",
        "stwo_cairo_cpu_integration",
        "--dep",
        "stwo_cairo_metal_integration",
        "--dep",
        "stwo_metal_session",
        "--dep",
        "stwo_proof_wire",
        "--dep",
        "stwo_native_examples",
        "--dep",
        "stwo_native_cuda_integration",
        "--dep",
        "stwo_cairo_cuda_integration",
        f"-Mroot={root_source}",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_metal_backend",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_riscv_frontend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_riscv_cpu_integration",
        "--dep",
        "stwo_cairo_cpu_integration",
        "--dep",
        "stwo_cairo_metal_integration",
        "--dep",
        "stwo_metal_session",
        "--dep",
        "stwo_proof_wire",
        "--dep",
        "stwo_native_examples",
        "--dep",
        "stwo_native_cuda_integration",
        "--dep",
        "stwo_cairo_cuda_integration",
        "-Mstwo=src/stwo.zig",
        "-Mstwo_core=src/core/mod.zig",
        "--dep",
        "stwo_core",
        "-Mstwo_proof_wire=src/interop/proof_wire/mod.zig",
        "--dep",
        "stwo_core",
        "-Mstwo_backend_contracts=src/backend/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "-Mstwo_prover_impl=src/prover/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cpu_backend=src/backends/cpu_scalar/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_proof_wire",
        "-Mstwo_native_examples=src/examples/mod.zig",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_native_examples",
        "--dep",
        "stwo_proof_wire",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_native_cuda_integration=src/integrations/native_cuda/mod.zig",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_cuda_backend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_native_cuda_integration",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cairo_cuda_integration=src/integrations/cairo_cuda/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "-Mstwo_metal_backend=src/backends/metal/mod.zig",
        "--dep",
        "stwo_backend_contracts",
        "-Mstwo_cuda_backend=src/backends/cuda/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_riscv_frontend=src/frontends/riscv/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cairo_frontend=src/frontends/cairo/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_riscv_frontend",
        "-Mstwo_riscv_cpu_integration=src/integrations/riscv_cpu/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_cairo_frontend",
        "-Mstwo_cairo_cpu_integration=src/integrations/cairo_cpu/mod.zig",
        "-Mstwo_metal_session=src/tools/metal_session/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_metal_backend",
        "--dep",
        "stwo_cairo_frontend",
        "--dep",
        "stwo_metal_session",
        "-Mstwo_cairo_metal_integration=src/integrations/cairo_metal/mod.zig",
        "--",
        *arguments,
    ]


def source_contract() -> tuple[Path, ...]:
    root = Path(__file__).resolve().parents[2]
    return (
        Path(__file__).resolve(),
        root / "src/core/mod.zig",
        root / "src/interop/proof_wire/mod.zig",
        root / "src/examples/mod.zig",
        root / "src/integrations/native_cuda/mod.zig",
        root / "src/backend/mod.zig",
        root / "src/prover/mod.zig",
        root / "src/backends/cpu_scalar/mod.zig",
        root / "src/backends/metal/mod.zig",
        root / "src/backends/cuda/mod.zig",
        root / "src/frontends/riscv/mod.zig",
        root / "src/frontends/cairo/mod.zig",
        root / "src/integrations/riscv_cpu/mod.zig",
        root / "src/integrations/cairo_cpu/mod.zig",
        root / "src/integrations/cairo_metal/mod.zig",
        root / "src/tools/metal_session/mod.zig",
    )
