#!/usr/bin/env python3
"""Deterministic RV32IM corpus and live Sail retirement-equivalence gate.

The vector programs are generated by the deterministic RV32IM assembler in
this file, committed as ELF fixtures under vectors/riscv_elfs/, and described
by vectors/riscv_elfs/trace_vectors.json. The gate rebuilds every ELF
in memory and requires byte identity with the committed fixture, then runs
the Zig `riscv-trace-dump` CLI over each fixture and requires the canonical
trace JSON to match the committed digest, step count, and final PC.

Modes:
  python3 scripts/riscv_trace_vectors.py            # gate (default)
  python3 scripts/riscv_trace_vectors.py --update   # regenerate fixtures
  python3 scripts/riscv_trace_vectors.py \
      --sail-bin /path/to/sail_riscv_sim --spike-bin /path/to/spike

The live mode verifies the Sail model/compiler/transport identity, compares
every architectural retirement field against that normative model, and
independently cross-checks the commit fields exposed by pinned Spike. Stark-V
remains recorded only as the legacy protocol-layout source and is never
consulted for ISA semantics.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import types
import subprocess
import sys
from pathlib import Path

try:
    from scripts import riscv_equivalence as equivalence
    from scripts.riscv_trace_vectors_lib import admission, classics, corpus, elf
    from scripts.riscv_trace_vectors_lib.encoders import (  # noqa: F401
        ADDI, XORI, ORI, ANDI, SLTI, SLTIU, SLLI, SRLI, SRAI, ADD, SUB, SLL, SLT, SLTU,
        XOR, SRL, SRA, OR, AND, MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM, REMU, LB, LH,
        LW, LBU, LHU, SB, SH, SW, BEQ, BNE, BLT, BGE, BLTU, BGEU, JAL, JALR, LUI,
        AUIPC, FENCE, ECALL,
    )
except ImportError:
    import riscv_equivalence as equivalence
    from riscv_trace_vectors_lib import admission, classics, corpus, elf
    from riscv_trace_vectors_lib.encoders import (  # noqa: F401
        ADDI, XORI, ORI, ANDI, SLTI, SLTIU, SLLI, SRLI, SRAI, ADD, SUB, SLL, SLT, SLTU,
        XOR, SRL, SRA, OR, AND, MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM, REMU, LB, LH,
        LW, LBU, LHU, SB, SH, SW, BEQ, BNE, BLT, BGE, BLTU, BGEU, JAL, JALR, LUI,
        AUIPC, FENCE, ECALL,
    )

ROOT = Path(__file__).resolve().parent.parent
VECTOR_DIR = ROOT / "vectors" / "riscv_elfs"
VECTOR_FILE = VECTOR_DIR / "trace_vectors.json"

# Derived from the comparator's own field tuples so the evidence report can
# never claim a field that compare_traces does not actually check.
SAIL_COMPARISON_FIELDS = (
    *equivalence.RETIREMENT_FIELDS,
    *(f"memory.{field}" for field in equivalence.MEMORY_FIELDS),
)
# Spike's scalar commit log exposes strictly less than RVFI; next_pc is only
# observable as the following commit's pc (see compare_spike_commit_trace).
SPIKE_COMPARISON_FIELDS = (
    "pc",
    "instruction",
    "rd",
    "rd_value",
    "next_pc (through the following commit)",
    "memory.address",
    "memory.write_value",
)


def comparison_digest(compared: list[dict]) -> str:
    """Digest binding an attestation to the exact per-program trace digests.

    scripts/riscv_sail_gate.py recomputes this from the committed manifest, so
    the digest is the one value that makes evidence-vs-corpus staleness
    mechanically detectable; changing the recipe orphans every committed
    attestation and requires regenerating the live evidence.
    """
    return _sha256(
        json.dumps(compared, sort_keys=True, separators=(",", ":")).encode()
    )

# ---------------------------------------------------------------------------
# RV32IM assembler (encoders follow the RISC-V unprivileged spec exactly)
# ---------------------------------------------------------------------------

CODE_VADDR = elf.CODE_VADDR
INPUT_START = elf.INPUT_START
INPUT_END = elf.INPUT_END
HALT_FLAG = elf.HALT_FLAG
OUTPUT_LEN = elf.OUTPUT_LEN
OUTPUT_DATA = elf.OUTPUT_DATA
STACK_BOTTOM = elf.STACK_BOTTOM
STACK_TOP = elf.STACK_TOP
GLOBAL_POINTER = elf.GLOBAL_POINTER
OUTPUT_END = elf.OUTPUT_END
MULTI_SHARD_LOOP_ITERATIONS = 65_536
MULTI_SHARD_ADDI_ROWS = MULTI_SHARD_LOOP_ITERATIONS + 2

build_elf_with_symbols = elf.build_elf_with_symbols
build_elf = elf.build_elf
release_symbols = elf.release_symbols
build_release_elf = elf.build_release_elf


# ---------------------------------------------------------------------------
# Vector programs — RV32IM coverage matrix, each halts via __halt_flag
# ---------------------------------------------------------------------------


def SENTINEL() -> int:
    """Legacy self-loop sentinel, retained only for a negative diagnostic."""
    return JAL(0, 0)


def EPILOGUE() -> list[int]:
    """Publish zero output bytes, then halt before the next instruction fetch."""
    return [LUI(31, HALT_FLAG), SW(0, 31, 4), ADDI(30, 0, 1), SW(30, 31, 0)]


def LEGACY_SENTINEL_EPILOGUE() -> list[int]:
    """Historical termination shape that leaves the halt flag unset."""
    return [LUI(31, HALT_FLAG), SW(0, 31, 4), SENTINEL()]


def prog_alu_basic() -> list[int]:
    return [ADDI(1, 0, 10), ADDI(2, 0, 20), ADD(3, 1, 2), SUB(4, 2, 1)] + EPILOGUE()


def prog_branch_fib() -> list[int]:
    return corpus.branch_fib_program(ADDI, ADD, BLT, BEQ, BNE, BGE, BLTU, BGEU, EPILOGUE())


def prog_mul_div() -> list[int]:
    return [
        ADDI(1, 0, -7),
        ADDI(2, 0, 3),
        MUL(3, 1, 2),  # -21
        MULH(4, 1, 2),  # high bits of signed product
        MULHU(5, 1, 2),  # unsigned view
        MULHSU(6, 1, 2),
        DIV(7, 1, 2),  # -2 (toward zero)
        REM(8, 1, 2),  # -1
        DIVU(9, 1, 2),
        REMU(10, 1, 2),
        ADDI(11, 0, 0),
        DIV(12, 1, 11),  # divide by zero => -1
        REM(13, 1, 11),  # rem by zero => dividend
        LUI(14, 0x80000000),  # INT_MIN
        ADDI(15, 0, -1),
        DIV(16, 14, 15),  # overflow => INT_MIN
        REM(17, 14, 15),  # overflow => 0
    ] + EPILOGUE()


def prog_mulhu_only() -> list[int]:
    """Exercise unsigned high multiplication as an independent family probe."""
    return [
        LUI(1, 0x80000000),
        ADDI(1, 1, -1),  # x1 = 0x7fffffff
        LUI(2, 0x40000000),
        MULHU(3, 1, 2),
    ] + EPILOGUE()


def prog_fence() -> list[int]:
    """Exercise canonical and reserved-field Base-I FENCE encodings."""
    return [
        ADDI(1, 0, 7),
        FENCE(),
        # Sail treats fm, rs1, and rd as reserved hints for base FENCE. They
        # carry no integer-register effect in this profile.
        FENCE(pred=0b0101, succ=0b1010, fm=0b0111, rs1=1, rd=2),
        ADDI(3, 1, 1),
    ] + EPILOGUE()


def prog_mem_ls() -> list[int]:
    return [
        LUI(1, 0x00100000),  # io RW region; offsets skip halt/len/output words
        LUI(2, 0x12345000),
        ADDI(2, 2, 0x678),  # x2 = 0x12345678
        SW(2, 1, 16),
        LW(3, 1, 16),
        SH(2, 1, 24),
        LHU(4, 1, 24),
        LH(5, 1, 24),  # sign-extended
        SB(2, 1, 32),
        LBU(6, 1, 32),
        LB(7, 1, 32),  # sign-extended
        AUIPC(8, 0),  # pc-relative
        SW(8, 1, 36),
        LW(9, 1, 36),
    ] + EPILOGUE()


def prog_shift_logic() -> list[int]:
    return [
        LUI(1, 0xF0F0F000),
        ADDI(1, 1, 0x0F0),
        ADDI(2, 0, 5),
        SLL(3, 1, 2),
        SRL(4, 1, 2),
        SRA(5, 1, 2),
        SLLI(6, 1, 12),
        SRLI(7, 1, 12),
        SRAI(8, 1, 12),
        AND(9, 1, 3),
        OR(10, 1, 4),
        XOR(11, 1, 5),
        ANDI(12, 1, 0x7F),
        ORI(13, 1, 0x55),
        XORI(14, 1, -1),  # bitwise NOT
        SLT(15, 5, 4),
        SLTU(16, 5, 4),
        SLTI(17, 1, 0),
        SLTIU(18, 1, 0),
    ] + EPILOGUE()


def prog_jal_jalr() -> list[int]:
    return [
        ADDI(1, 0, 0),  # 0x10000
        JAL(5, 12),  # 0x10004: call fn at 0x10010, x5 = 0x10008
        ADDI(1, 1, 100),  # 0x10008: return lands here
        JAL(0, 12),  # 0x1000C: jump over fn body to end at 0x10018
        ADDI(1, 1, 1),  # 0x10010: fn body
        JALR(0, 5, 0),  # 0x10014: return to x5
        ADDI(2, 1, 0),  # 0x10018: end
    ] + EPILOGUE()


def prog_declared_region() -> list[int]:
    # Retained as a named program-root fixture; every positive vector now has a
    # declared text region and explicit I/O symbols.
    return [ADDI(1, 0, 10), ADDI(2, 0, 20), ADD(3, 1, 2), SUB(4, 2, 1)] + EPILOGUE()


def prog_multi_shard_addi() -> list[int]:
    """Compact loop that produces more than one base-ALU-immediate shard."""
    return [
        ADDI(1, 0, 0),
        LUI(2, MULTI_SHARD_LOOP_ITERATIONS),
        ADDI(1, 1, 1),
        BLT(1, 2, -4),
    ] + EPILOGUE()


def _encoder_namespace() -> types.SimpleNamespace:
    """Expose the uppercase encoder callables to the classics library."""
    return types.SimpleNamespace(
        **{n: v for n, v in globals().items() if n.isupper() and callable(v)}
    )


PROGRAMS: dict[str, list[int]] = {
    "alu_test": prog_alu_basic(),
    "branch_fib": prog_branch_fib(),
    "declared_region": prog_declared_region(),
    "fence": prog_fence(),
    "mul_div": prog_mul_div(),
    "mulhu_only": prog_mulhu_only(),
    "mem_ls": prog_mem_ls(),
    "multi_shard_addi": prog_multi_shard_addi(),
    "shift_logic": prog_shift_logic(),
    "jal_jalr": prog_jal_jalr(),
    **classics.all_programs(_encoder_namespace()),
}


PROOF_ADMISSION = admission.for_programs(PROGRAMS)


NEGATIVE_FIXTURES: dict[str, tuple[bytes, str]] = {
    "undeclared_program": (
        build_elf(prog_alu_basic()),
        "missing_declared_program_symbols",
    ),
    "self_loop_sentinel": (
        build_release_elf(
            [ADDI(1, 0, 10), ADDI(2, 0, 20), ADD(3, 1, 2), SUB(4, 2, 1)]
            + LEGACY_SENTINEL_EPILOGUE()
        ),
        "self_loop_terminates_without_setting_halt_flag",
    ),
    "illegal_opcode": (
        build_release_elf([0xFFFF_FFFF]),
        "illegal_primary_opcode",
    ),
    "reserved_op_funct7": (
        build_release_elf([0x2000_0033]),
        "reserved_op_funct7",
    ),
    "fence_i_outside_profile": (
        build_release_elf([0x0000_100F]),
        "zifencei_outside_rv32im_profile",
    ),
    "misaligned_jump_target": (
        build_release_elf([JAL(0, 2)]),
        "instruction_address_misaligned",
    ),
    "misaligned_word_load": (
        build_release_elf([LW(1, 0, 2)]),
        "data_address_misaligned",
    ),
    "system_ecall": (
        build_release_elf([ECALL()]),
        "system_instruction_is_environment_control",
    ),
}

FORMAL_WORD_DISPOSITIONS = {
    "illegal_opcode": (0xFFFF_FFFF, True),
    "reserved_op_funct7": (0x2000_0033, True),
    # The pinned Sail decoder currently retires FENCE.I even when its
    # configuration reports rv32im with Zifencei disabled. The zkVM rejects
    # that extra-extension encoding at its explicitly narrower ingress.
    "fence_i_outside_profile": (0x0000_100F, False),
    "misaligned_jump_target": (JAL(0, 2), True),
    "misaligned_word_load": (LW(1, 0, 2), True),
    "system_ecall": (ECALL(), True),
}


# ---------------------------------------------------------------------------
# Gate / update machinery
# ---------------------------------------------------------------------------


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def formal_profile() -> dict:
    path = ROOT / "conformance" / "riscv" / "rv32im-sail-profile.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    if (
        value.get("schema") != "stwo-riscv-formal-profile-v1"
        or value.get("name") != equivalence.PROFILE
    ):
        raise SystemExit(f"{path}: unsupported formal profile")
    return value


def manifest_identity() -> dict:
    profile = formal_profile()
    return {
        "schema": "stwo-riscv-formal-corpus-v1",
        "profile": profile["name"],
        "authorities": profile["authorities"],
        "rvfi_transport": profile["rvfi_transport"],
        "legacy_protocol_layout": profile["legacy_protocol_layout"],
    }


def build_trace_dumper() -> Path:
    subprocess.run(
        ["zig", "build", "riscv-trace-dump", "-Doptimize=ReleaseFast"],
        cwd=ROOT,
        check=True,
    )
    return ROOT / "zig-out" / "bin" / "riscv-trace-dump"


def dump_trace(dumper: Path, elf_path: Path, out_path: Path) -> bytes:
    subprocess.run(
        [str(dumper), "--elf", str(elf_path), "--output", str(out_path)],
        cwd=ROOT,
        check=True,
    )
    return out_path.read_bytes()


def _negative_sail_disposition(name: str) -> str:
    formal = FORMAL_WORD_DISPOSITIONS.get(name)
    if formal is None:
        return "zkvm_environment_only"
    return "trap" if formal[1] else "retire_profile_exclusion"


def update(scratch: Path) -> int:
    VECTOR_DIR.mkdir(parents=True, exist_ok=True)
    negative_dir = VECTOR_DIR / "negative"
    negative_dir.mkdir(parents=True, exist_ok=True)
    dumper = build_trace_dumper()
    vectors = []
    corpus_opcode_ids: set[int] = set()
    all_programs = {
        name: build_release_elf(program) for name, program in PROGRAMS.items()
    }
    for name in sorted(all_programs):
        elf_bytes = all_programs[name]
        elf_path = VECTOR_DIR / f"{name}.elf"
        elf_path.write_bytes(elf_bytes)
        trace_bytes = dump_trace(dumper, elf_path, scratch / f"{name}.trace.json")
        trace = json.loads(trace_bytes)
        opcode_ids = corpus.executed_opcode_ids(dumper, elf_path, trace, ROOT)
        corpus_opcode_ids.update(opcode_ids)
        vectors.append(
            {
                "name": name,
                "elf": f"vectors/riscv_elfs/{name}.elf",
                "elf_sha256": _sha256(elf_bytes),
                "trace_sha256": _sha256(trace_bytes),
                "total_steps": trace["total_steps"],
                "final_pc": trace["final_pc"],
                "executed_opcode_ids": opcode_ids,
                "proof_admission": PROOF_ADMISSION[name],
            }
        )
    if corpus_opcode_ids != corpus.EXPECTED_PROOF_OPCODE_IDS:
        missing = sorted(corpus.EXPECTED_PROOF_OPCODE_IDS - corpus_opcode_ids)
        extra = sorted(corpus_opcode_ids - corpus.EXPECTED_PROOF_OPCODE_IDS)
        raise SystemExit(f"release corpus opcode IDs differ: missing={missing} extra={extra}")
    negative_vectors = []
    for name in sorted(NEGATIVE_FIXTURES):
        elf_bytes, reason = NEGATIVE_FIXTURES[name]
        elf_path = negative_dir / f"{name}.elf"
        elf_path.write_bytes(elf_bytes)
        negative_vectors.append(
            {
                "name": name,
                "elf": f"vectors/riscv_elfs/negative/{name}.elf",
                "elf_sha256": _sha256(elf_bytes),
                "expected": "diagnostic_only_not_release_eligible",
                "reason": reason,
            }
        )
    payload = {
        **manifest_identity(),
        "captured_by": "scripts/riscv_trace_vectors.py --update",
        "formal_verification": {
            "tool": "scripts/riscv_trace_vectors.py --sail-bin --spike-bin",
            "comparison": (
                "every canonical RVFI-shaped field against Sail; every scalar "
                "commit-log field exposed by independently pinned Spike"
            ),
            "policy": "live external authority required for formal/release evidence",
        },
        "vectors": vectors,
        "negative_vectors": negative_vectors,
    }
    for vector in payload["negative_vectors"]:
        vector["expected"] = "zig_reject_before_retirement"
        vector["sail_disposition"] = _negative_sail_disposition(vector["name"])
    VECTOR_FILE.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {VECTOR_FILE} with {len(vectors)} vectors")
    return 0


def gate(
    scratch: Path,
    sail_bin: Path | None = None,
    spike_bin: Path | None = None,
    formal_report: Path | None = None,
    trace_dump_bin: Path | None = None,
) -> int:
    if not VECTOR_FILE.exists():
        print("riscv trace vectors: missing vectors/riscv_elfs/trace_vectors.json", file=sys.stderr)
        return 1
    if trace_dump_bin is not None and not trace_dump_bin.is_file():
        print(
            f"riscv trace vectors: --trace-dump-bin {trace_dump_bin} does not exist",
            file=sys.stderr,
        )
        return 1
    payload = json.loads(VECTOR_FILE.read_text(encoding="utf-8"))
    errors: list[str] = []
    for field, expected_value in manifest_identity().items():
        if payload.get(field) != expected_value:
            errors.append(f"vector manifest {field} does not match the formal profile")
    recorded = {v["name"] for v in payload.get("vectors", [])}
    expected = set(PROGRAMS)
    if recorded != expected:
        errors.append(f"vector set mismatch: recorded {sorted(recorded)} expected {sorted(expected)}")

    errors.extend(admission.errors(payload.get("vectors", []), PROOF_ADMISSION))

    dumper = trace_dump_bin or build_trace_dumper()
    corpus_opcode_ids: set[int] = set()
    for vector in payload.get("vectors", []):
        name = vector["name"]
        program = PROGRAMS.get(name)
        if program is None:
            continue
        elf_path = ROOT / vector["elf"]
        if not elf_path.exists():
            errors.append(f"{name}: committed ELF missing at {vector['elf']}")
            continue
        committed = elf_path.read_bytes()
        regenerated = build_release_elf(program)
        if committed != regenerated:
            errors.append(f"{name}: committed ELF is not byte-identical to the generator output")
            continue
        if _sha256(committed) != vector["elf_sha256"]:
            errors.append(f"{name}: ELF digest drift")
            continue
        trace_bytes = dump_trace(dumper, elf_path, scratch / f"{name}.trace.json")
        if _sha256(trace_bytes) != vector["trace_sha256"]:
            errors.append(f"{name}: trace digest drift (executor semantics changed?)")
            continue
        trace = json.loads(trace_bytes)
        if trace["total_steps"] != vector["total_steps"]:
            errors.append(
                f"{name}: step count {trace['total_steps']} != recorded {vector['total_steps']}"
            )
        if trace["final_pc"] != vector["final_pc"]:
            errors.append(f"{name}: final pc {trace['final_pc']} != recorded {vector['final_pc']}")
        try:
            opcode_ids = corpus.executed_opcode_ids(dumper, elf_path, trace, ROOT)
        except ValueError as error:
            errors.append(f"{name}: {error}")
            continue
        if opcode_ids != vector.get("executed_opcode_ids"):
            errors.append(f"{name}: executed opcode ID coverage drift")
        corpus_opcode_ids.update(opcode_ids)

    if corpus_opcode_ids != corpus.EXPECTED_PROOF_OPCODE_IDS:
        missing = sorted(corpus.EXPECTED_PROOF_OPCODE_IDS - corpus_opcode_ids)
        extra = sorted(corpus_opcode_ids - corpus.EXPECTED_PROOF_OPCODE_IDS)
        errors.append(f"release corpus opcode IDs differ: missing={missing} extra={extra}")

    recorded_negative = {v["name"] for v in payload.get("negative_vectors", [])}
    if recorded_negative != set(NEGATIVE_FIXTURES):
        errors.append(
            "negative vector set mismatch: recorded "
            f"{sorted(recorded_negative)} expected {sorted(NEGATIVE_FIXTURES)}"
        )
    for vector in payload.get("negative_vectors", []):
        name = vector["name"]
        fixture = NEGATIVE_FIXTURES.get(name)
        if fixture is None:
            continue
        regenerated, reason = fixture
        elf_path = ROOT / vector["elf"]
        if not elf_path.exists():
            errors.append(f"{name}: committed negative ELF missing at {vector['elf']}")
            continue
        committed = elf_path.read_bytes()
        if committed != regenerated:
            errors.append(f"{name}: negative ELF is not byte-identical to generator output")
        if _sha256(committed) != vector.get("elf_sha256"):
            errors.append(f"{name}: negative ELF digest drift")
        if vector.get("expected") != "zig_reject_before_retirement":
            errors.append(f"{name}: negative fixture is not a fail-closed ingress check")
        if vector.get("reason") != reason:
            errors.append(f"{name}: negative fixture reason drift")
        if vector.get("sail_disposition") != _negative_sail_disposition(name):
            errors.append(f"{name}: Sail disposition drift")
        if name in FORMAL_WORD_DISPOSITIONS:
            rejected = subprocess.run(
                [
                    str(dumper),
                    "--elf",
                    str(elf_path),
                    "--output",
                    str(scratch / f"{name}.unexpected.json"),
                    "--max-steps",
                    "2",
                ],
                cwd=ROOT,
                capture_output=True,
            )
            if rejected.returncode == 0:
                errors.append(f"{name}: Zig runner unexpectedly retired the negative fixture")

    if errors:
        for error in errors:
            print(f"riscv trace vectors: {error}", file=sys.stderr)
        return 1
    print(
        f"riscv trace vectors: {len(payload['vectors'])} positive and "
        f"{len(payload['negative_vectors'])} negative fixtures reproduced for "
        f"{payload['profile']}"
    )
    if sail_bin is not None or spike_bin is not None:
        return attest_formal(
            payload,
            sail_bin,
            spike_bin,
            dumper,
            formal_report,
        )
    return 0


def attest_formal(
    payload: dict,
    sail_bin: Path | None,
    spike_bin: Path | None,
    zig_dumper: Path,
    report_path: Path | None,
) -> int:
    """Cross-run the corpus against normative Sail and independent Spike."""
    sail_identity = None
    spike_identity = None
    try:
        if sail_bin is not None:
            sail_bin = sail_bin.resolve(strict=True)
            sail_identity = equivalence.verify_sail_binary(sail_bin)
        if spike_bin is not None:
            spike_bin = spike_bin.resolve(strict=True)
            spike_identity = equivalence.verify_spike_binary(spike_bin)
    except (OSError, equivalence.EquivalenceError, subprocess.SubprocessError) as error:
        print(f"riscv trace vectors: formal-tool identity failed: {error}", file=sys.stderr)
        return 1

    total_retirements = 0
    compared: list[dict] = []
    for vector in payload["vectors"]:
        elf_path = ROOT / vector["elf"]
        try:
            zig_trace = equivalence.run_zig_trace(
                elf_path,
                zig_dumper,
                vector["total_steps"] + 1,
                None,
            )
            if sail_bin is not None:
                sail_trace = equivalence.run_sail_rvfi_dii(sail_bin, zig_trace)
                differences = equivalence.compare_traces(sail_trace, zig_trace)
                if differences:
                    for difference in differences:
                        print(
                            f"riscv trace vectors: {vector['name']}: "
                            f"Sail: {difference}",
                            file=sys.stderr,
                        )
                    return 1
            if spike_bin is not None:
                spike_rows = equivalence.run_spike_commit_trace(
                    spike_bin,
                    elf_path,
                    zig_trace,
                )
                differences = equivalence.compare_spike_commit_trace(
                    spike_rows,
                    zig_trace,
                )
                if differences:
                    for difference in differences:
                        print(
                            f"riscv trace vectors: {vector['name']}: "
                            f"Spike: {difference}",
                            file=sys.stderr,
                        )
                    return 1
        except (
            OSError,
            equivalence.EquivalenceError,
            subprocess.SubprocessError,
        ) as error:
            print(f"riscv trace vectors: {vector['name']}: {error}", file=sys.stderr)
            return 1
        total_retirements += zig_trace["total_steps"]
        compared.append(
            {
                "name": vector["name"],
                "retirements": zig_trace["total_steps"],
                "trace_sha256": vector["trace_sha256"],
            }
        )
        comparisons = []
        if sail_bin is not None:
            comparisons.append("Sail/Zig")
        if spike_bin is not None:
            comparisons.append("Spike/Zig")
        print(
            f"{vector['name']}: {' and '.join(comparisons)} equivalent "
            f"({zig_trace['total_steps']} retirements)"
        )

    for name, (instruction, expect_trap) in FORMAL_WORD_DISPOSITIONS.items():
        negative_elf = ROOT / next(
            vector["elf"]
            for vector in payload["negative_vectors"]
            if vector["name"] == name
        )
        try:
            if sail_bin is not None:
                equivalence.run_sail_word(
                    sail_bin,
                    instruction,
                    expect_trap=expect_trap,
                )
            if spike_bin is not None:
                equivalence.run_spike_disposition(
                    spike_bin,
                    negative_elf,
                    instruction,
                    expect_trap=expect_trap,
                )
        except (
            OSError,
            equivalence.EquivalenceError,
            subprocess.SubprocessError,
        ) as error:
            print(f"riscv trace vectors: {name}: {error}", file=sys.stderr)
            return 1
        disposition = "trap" if expect_trap else "retire (profile exclusion)"
        simulators = []
        if sail_bin is not None:
            simulators.append("Sail")
        if spike_bin is not None:
            simulators.append("Spike")
        print(
            f"{name}: {'/'.join(simulators)} disposition {disposition}; "
            "Zig rejected before retirement"
        )

    digest = comparison_digest(compared)
    report = {
        "schema": "stwo-riscv-formal-corpus-evidence-v1",
        "profile": payload["profile"],
        "result": "equivalent",
        "semantic_authority": "Sail",
        "sail": sail_identity,
        "independent_cross_check": "Spike",
        "spike": spike_identity,
        "programs": len(compared),
        "retirements": total_retirements,
        "negative_decode_and_trap_cases": len(FORMAL_WORD_DISPOSITIONS),
        "comparison_digest": digest,
        "comparison_fields": list(SAIL_COMPARISON_FIELDS),
        "spike_comparison_fields": list(SPIKE_COMPARISON_FIELDS),
    }
    if report_path is not None:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(
        f"riscv formal corpus: PASS ({len(compared)} programs, "
        f"{total_retirements} retirements, digest {digest})"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="regenerate fixtures and digests")
    parser.add_argument(
        "--sail-bin",
        type=Path,
        metavar="SAIL_RISCV_SIM",
        help="run the live pinned Sail differential after the deterministic gate",
    )
    parser.add_argument(
        "--spike-bin",
        type=Path,
        metavar="SPIKE",
        help="run the independently pinned Spike commit cross-check",
    )
    parser.add_argument(
        "--formal-report",
        type=Path,
        help="write formal evidence (requires both --sail-bin and --spike-bin)",
    )
    # Digest parity fails loudly on a stale executor, so the gate may take a
    # prebuilt dumper; hosted gates and --update must keep building from the
    # checkout so the executor under test is the code under review.
    parser.add_argument(
        "--trace-dump-bin",
        type=Path,
        metavar="RISCV_TRACE_DUMP",
        help="prebuilt riscv-trace-dump for local runs that must not `zig build`",
    )
    parser.add_argument("--scratch", type=Path, default=None, help="working dir for trace output")
    args = parser.parse_args(argv)
    import tempfile

    def dispatch(scratch: Path) -> int:
        if args.update:
            if (
                args.sail_bin is not None
                or args.spike_bin is not None
                or args.formal_report is not None
                or args.trace_dump_bin is not None
            ):
                parser.error("--update cannot be combined with live formal options")
            return update(scratch)
        if args.formal_report is not None and (
            args.sail_bin is None or args.spike_bin is None
        ):
            parser.error("--formal-report requires --sail-bin and --spike-bin")
        return gate(
            scratch,
            args.sail_bin,
            args.spike_bin,
            args.formal_report,
            args.trace_dump_bin,
        )

    if args.scratch is not None:
        args.scratch.mkdir(parents=True, exist_ok=True)
        return dispatch(args.scratch)
    with tempfile.TemporaryDirectory() as tmp:
        return dispatch(Path(tmp))


if __name__ == "__main__":
    raise SystemExit(main())
