#!/usr/bin/env python3
"""Gated RISC-V trace vectors against the pinned Stark-V oracle lane.

The vector programs are generated by the deterministic RV32IM assembler in
this file, committed as ELF fixtures under vectors/riscv_elfs/, and described
by vectors/riscv_elfs/trace_vectors.json. The gate rebuilds every ELF
in memory and requires byte identity with the committed fixture, then runs
the Zig `riscv-trace-dump` CLI over each fixture and requires the canonical
trace JSON to match the committed digest, step count, and final PC.

Modes:
  python3 scripts/riscv_trace_vectors.py            # gate (default)
  python3 scripts/riscv_trace_vectors.py --update   # regenerate fixtures

Cross-verification provenance against the Rust Stark-V runner at the pinned
revision is recorded in the vector file. The attestation mode requires an
exact, clean Stark-V source checkout and byte-compares its adapter output with
the Zig runner's canonical trace JSON.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VECTOR_DIR = ROOT / "vectors" / "riscv_elfs"
VECTOR_FILE = VECTOR_DIR / "trace_vectors.json"

# ---------------------------------------------------------------------------
# RV32IM assembler (encoders follow the RISC-V unprivileged spec exactly)
# ---------------------------------------------------------------------------

CODE_VADDR = 0x0001_0000


def _mask(value: int, bits: int) -> int:
    return value & ((1 << bits) - 1)


def enc_r(funct7: int, rs2: int, rs1: int, funct3: int, rd: int, opcode: int) -> int:
    return funct7 << 25 | rs2 << 20 | rs1 << 15 | funct3 << 12 | rd << 7 | opcode


def enc_i(imm: int, rs1: int, funct3: int, rd: int, opcode: int) -> int:
    return _mask(imm, 12) << 20 | rs1 << 15 | funct3 << 12 | rd << 7 | opcode


def enc_s(imm: int, rs2: int, rs1: int, funct3: int, opcode: int) -> int:
    imm = _mask(imm, 12)
    return (imm >> 5) << 25 | rs2 << 20 | rs1 << 15 | funct3 << 12 | (imm & 0x1F) << 7 | opcode


def enc_b(imm: int, rs2: int, rs1: int, funct3: int, opcode: int) -> int:
    imm = _mask(imm, 13)
    return (
        (imm >> 12) << 31
        | ((imm >> 5) & 0x3F) << 25
        | rs2 << 20
        | rs1 << 15
        | funct3 << 12
        | ((imm >> 1) & 0xF) << 8
        | ((imm >> 11) & 0x1) << 7
        | opcode
    )


def enc_u(imm: int, rd: int, opcode: int) -> int:
    return _mask(imm, 32) & 0xFFFFF000 | rd << 7 | opcode


def enc_j(imm: int, rd: int, opcode: int) -> int:
    imm = _mask(imm, 21)
    return (
        (imm >> 20) << 31
        | ((imm >> 1) & 0x3FF) << 21
        | ((imm >> 11) & 0x1) << 20
        | ((imm >> 12) & 0xFF) << 12
        | rd << 7
        | opcode
    )


def ADDI(rd, rs1, imm):
    return enc_i(imm, rs1, 0x0, rd, 0x13)


def XORI(rd, rs1, imm):
    return enc_i(imm, rs1, 0x4, rd, 0x13)


def ORI(rd, rs1, imm):
    return enc_i(imm, rs1, 0x6, rd, 0x13)


def ANDI(rd, rs1, imm):
    return enc_i(imm, rs1, 0x7, rd, 0x13)


def SLTI(rd, rs1, imm):
    return enc_i(imm, rs1, 0x2, rd, 0x13)


def SLTIU(rd, rs1, imm):
    return enc_i(imm, rs1, 0x3, rd, 0x13)


def SLLI(rd, rs1, sh):
    return enc_i(sh, rs1, 0x1, rd, 0x13)


def SRLI(rd, rs1, sh):
    return enc_i(sh, rs1, 0x5, rd, 0x13)


def SRAI(rd, rs1, sh):
    return enc_i(0x400 | sh, rs1, 0x5, rd, 0x13)


def ADD(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x0, rd, 0x33)


def SUB(rd, rs1, rs2):
    return enc_r(0x20, rs2, rs1, 0x0, rd, 0x33)


def SLL(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x1, rd, 0x33)


def SLT(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x2, rd, 0x33)


def SLTU(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x3, rd, 0x33)


def XOR(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x4, rd, 0x33)


def SRL(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x5, rd, 0x33)


def SRA(rd, rs1, rs2):
    return enc_r(0x20, rs2, rs1, 0x5, rd, 0x33)


def OR(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x6, rd, 0x33)


def AND(rd, rs1, rs2):
    return enc_r(0x00, rs2, rs1, 0x7, rd, 0x33)


def MUL(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x0, rd, 0x33)


def MULH(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x1, rd, 0x33)


def MULHSU(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x2, rd, 0x33)


def MULHU(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x3, rd, 0x33)


def DIV(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x4, rd, 0x33)


def DIVU(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x5, rd, 0x33)


def REM(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x6, rd, 0x33)


def REMU(rd, rs1, rs2):
    return enc_r(0x01, rs2, rs1, 0x7, rd, 0x33)


def LB(rd, rs1, imm):
    return enc_i(imm, rs1, 0x0, rd, 0x03)


def LH(rd, rs1, imm):
    return enc_i(imm, rs1, 0x1, rd, 0x03)


def LW(rd, rs1, imm):
    return enc_i(imm, rs1, 0x2, rd, 0x03)


def LBU(rd, rs1, imm):
    return enc_i(imm, rs1, 0x4, rd, 0x03)


def LHU(rd, rs1, imm):
    return enc_i(imm, rs1, 0x5, rd, 0x03)


def SB(rs2, rs1, imm):
    return enc_s(imm, rs2, rs1, 0x0, 0x23)


def SH(rs2, rs1, imm):
    return enc_s(imm, rs2, rs1, 0x1, 0x23)


def SW(rs2, rs1, imm):
    return enc_s(imm, rs2, rs1, 0x2, 0x23)


def BEQ(rs1, rs2, imm):
    return enc_b(imm, rs2, rs1, 0x0, 0x63)


def BNE(rs1, rs2, imm):
    return enc_b(imm, rs2, rs1, 0x1, 0x63)


def BLT(rs1, rs2, imm):
    return enc_b(imm, rs2, rs1, 0x4, 0x63)


def BGE(rs1, rs2, imm):
    return enc_b(imm, rs2, rs1, 0x5, 0x63)


def BLTU(rs1, rs2, imm):
    return enc_b(imm, rs2, rs1, 0x6, 0x63)


def BGEU(rs1, rs2, imm):
    return enc_b(imm, rs2, rs1, 0x7, 0x63)


def JAL(rd, imm):
    return enc_j(imm, rd, 0x6F)


def JALR(rd, rs1, imm):
    return enc_i(imm, rs1, 0x0, rd, 0x67)


def LUI(rd, imm):
    return enc_u(imm, rd, 0x37)


def AUIPC(rd, imm):
    return enc_u(imm, rd, 0x17)


def ECALL():
    return 0x0000_0073


def build_elf(instructions: list[int]) -> bytes:
    """Minimal RV32 ELF: 52-byte header + one PT_LOAD phdr + code at 0x10000.

    Byte-compatible with the historical alu_test.elf fixture layout.
    """
    code = b"".join(struct.pack("<I", inst) for inst in instructions)
    e_phoff = 52
    code_off = 52 + 32
    header = struct.pack(
        "<4sBBBBB7xHHIIIIIHHHHHH",
        b"\x7fELF",
        1,  # 32-bit
        1,  # little-endian
        1,  # EV_CURRENT
        0,  # System V ABI
        0,  # ABI version
        2,  # ET_EXEC
        0xF3,  # EM_RISCV
        1,  # e_version
        CODE_VADDR,  # e_entry
        e_phoff,
        0,  # e_shoff
        0,  # e_flags
        52,  # e_ehsize
        32,  # e_phentsize
        1,  # e_phnum
        0,  # e_shentsize
        0,  # e_shnum
        0,  # e_shstrndx
    )
    phdr = struct.pack(
        "<IIIIIIII",
        1,  # PT_LOAD
        code_off,  # p_offset
        CODE_VADDR,  # p_vaddr
        0,  # p_paddr
        len(code),  # p_filesz
        len(code),  # p_memsz
        0,  # p_flags (loader ignores)
        0,  # p_align (matches the historical fixture)
    )
    return header + phdr + code


# ---------------------------------------------------------------------------
# Vector programs — RV32IM coverage matrix, each halts via ECALL
# ---------------------------------------------------------------------------


def SENTINEL() -> int:
    """Stark-V halt sentinel: `jal x0, 0` — both runners halt without tracing it."""
    return JAL(0, 0)


def EPILOGUE() -> list[int]:
    """SDK-conforming halt: write the zero output-length word (the pinned
    oracle's PublicData builder requires the output-len address to have been
    accessed), then the sentinel."""
    return [LUI(31, 0x00100000), SW(0, 31, 4), SENTINEL()]


def prog_alu_basic() -> list[int]:
    return [ADDI(1, 0, 10), ADDI(2, 0, 20), ADD(3, 1, 2), SUB(4, 2, 1)] + EPILOGUE()


def prog_branch_fib() -> list[int]:
    # fib(24) iteratively: x1=a, x2=b, x3=i, x4=n, x5=tmp
    return [
        ADDI(1, 0, 0),
        ADDI(2, 0, 1),
        ADDI(3, 0, 0),
        ADDI(4, 0, 24),
        # loop:
        ADD(5, 1, 2),  # tmp = a + b
        ADDI(1, 2, 0),  # a = b
        ADDI(2, 5, 0),  # b = tmp
        ADDI(3, 3, 1),  # i += 1
        BLT(3, 4, -16),  # while i < n
        BEQ(1, 2, 8),  # never taken (a != b after loop)
        ADDI(6, 0, 1),  # x6 = 1 marks fallthrough
    ] + EPILOGUE()


def prog_mul_div() -> list[int]:
    return [
        ADDI(1, 0, -7),
        ADDI(2, 0, 3),
        MUL(3, 1, 2),  # -21
        MULH(4, 1, 2),  # high bits of signed product
        MULHU(5, 1, 2),  # unsigned view
        MULHSU(6, 1, 2),
        DIV(7, 1, 2),  # -2 (toward zero)
        REM(8, 1, 2),  # -1
        DIVU(9, 1, 2),
        REMU(10, 1, 2),
        ADDI(11, 0, 0),
        DIV(12, 1, 11),  # divide by zero => -1
        REM(13, 1, 11),  # rem by zero => dividend
        LUI(14, 0x80000000),  # INT_MIN
        ADDI(15, 0, -1),
        DIV(16, 14, 15),  # overflow => INT_MIN
        REM(17, 14, 15),  # overflow => 0
    ] + EPILOGUE()


def prog_mem_ls() -> list[int]:
    return [
        LUI(1, 0x00100000),  # io RW region; offsets skip halt/len/output words
        LUI(2, 0x12345000),
        ADDI(2, 2, 0x678),  # x2 = 0x12345678
        SW(2, 1, 16),
        LW(3, 1, 16),
        SH(2, 1, 24),
        LHU(4, 1, 24),
        LH(5, 1, 24),  # sign-extended
        SB(2, 1, 32),
        LBU(6, 1, 32),
        LB(7, 1, 32),  # sign-extended
        AUIPC(8, 0),  # pc-relative
        SW(8, 1, 36),
        LW(9, 1, 36),
    ] + EPILOGUE()


def prog_shift_logic() -> list[int]:
    return [
        LUI(1, 0xF0F0F000),
        ADDI(1, 1, 0x0F0),
        ADDI(2, 0, 5),
        SLL(3, 1, 2),
        SRL(4, 1, 2),
        SRA(5, 1, 2),
        SLLI(6, 1, 12),
        SRLI(7, 1, 12),
        SRAI(8, 1, 12),
        AND(9, 1, 3),
        OR(10, 1, 4),
        XOR(11, 1, 5),
        ANDI(12, 1, 0x7F),
        ORI(13, 1, 0x55),
        XORI(14, 1, -1),  # bitwise NOT
        SLT(15, 5, 4),
        SLTU(16, 5, 4),
        SLTI(17, 1, 0),
        SLTIU(18, 1, 0),
    ] + EPILOGUE()


def prog_jal_jalr() -> list[int]:
    return [
        ADDI(1, 0, 0),  # 0x10000
        JAL(5, 12),  # 0x10004: call fn at 0x10010, x5 = 0x10008
        ADDI(1, 1, 100),  # 0x10008: return lands here
        JAL(0, 12),  # 0x1000C: jump over fn body to end at 0x10018
        ADDI(1, 1, 1),  # 0x10010: fn body
        JALR(0, 5, 0),  # 0x10014: return to x5
        ADDI(2, 1, 0),  # 0x10018: end
    ] + EPILOGUE()


PROGRAMS: dict[str, list[int]] = {
    "alu_test": prog_alu_basic(),
    "branch_fib": prog_branch_fib(),
    "mul_div": prog_mul_div(),
    "mem_ls": prog_mem_ls(),
    "shift_logic": prog_shift_logic(),
    "jal_jalr": prog_jal_jalr(),
}


# ---------------------------------------------------------------------------
# Gate / update machinery
# ---------------------------------------------------------------------------


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def pinned_stark_v_commit() -> str:
    text = (ROOT / "conformance" / "upstream.md").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("- Pinned Stark-V commit: `"):
            return line.split("`")[1]
    raise SystemExit("conformance/upstream.md has no pinned Stark-V commit")


def build_trace_dumper() -> Path:
    subprocess.run(
        ["zig", "build", "riscv-trace-dump", "-Doptimize=ReleaseFast"],
        cwd=ROOT,
        check=True,
    )
    return ROOT / "zig-out" / "bin" / "riscv-trace-dump"


def dump_trace(dumper: Path, elf_path: Path, out_path: Path) -> bytes:
    subprocess.run(
        [str(dumper), "--elf", str(elf_path), "--output", str(out_path)],
        cwd=ROOT,
        check=True,
    )
    return out_path.read_bytes()


def update(scratch: Path) -> int:
    VECTOR_DIR.mkdir(parents=True, exist_ok=True)
    dumper = build_trace_dumper()
    vectors = []
    for name, program in sorted(PROGRAMS.items()):
        elf_bytes = build_elf(program)
        elf_path = VECTOR_DIR / f"{name}.elf"
        elf_path.write_bytes(elf_bytes)
        trace_bytes = dump_trace(dumper, elf_path, scratch / f"{name}.trace.json")
        trace = json.loads(trace_bytes)
        vectors.append(
            {
                "name": name,
                "elf": f"vectors/riscv_elfs/{name}.elf",
                "elf_sha256": _sha256(elf_bytes),
                "trace_sha256": _sha256(trace_bytes),
                "total_steps": trace["total_steps"],
                "final_pc": trace["final_pc"],
            }
        )
    payload = {
        "stark_v_commit": pinned_stark_v_commit(),
        "captured_by": "scripts/riscv_trace_vectors.py --update",
        "cross_verification": {
            "tool": "scripts/riscv_equivalence.py --run",
            "status": "zig-only",
            "note": "digests captured from the Zig runner; rerun the equivalence "
            "tool against a Stark-V dumper built at the pinned commit to "
            "escalate provenance",
        },
        "vectors": vectors,
    }
    VECTOR_FILE.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {VECTOR_FILE} with {len(vectors)} vectors")
    return 0


def gate(scratch: Path) -> int:
    if not VECTOR_FILE.exists():
        print("riscv trace vectors: missing vectors/riscv_elfs/trace_vectors.json", file=sys.stderr)
        return 1
    payload = json.loads(VECTOR_FILE.read_text(encoding="utf-8"))
    errors: list[str] = []
    if payload.get("stark_v_commit") != pinned_stark_v_commit():
        errors.append("vector provenance commit does not match the pinned Stark-V commit")
    recorded = {v["name"] for v in payload.get("vectors", [])}
    expected = set(PROGRAMS)
    if recorded != expected:
        errors.append(f"vector set mismatch: recorded {sorted(recorded)} expected {sorted(expected)}")

    dumper = build_trace_dumper()
    for vector in payload.get("vectors", []):
        name = vector["name"]
        program = PROGRAMS.get(name)
        if program is None:
            continue
        elf_path = ROOT / vector["elf"]
        if not elf_path.exists():
            errors.append(f"{name}: committed ELF missing at {vector['elf']}")
            continue
        committed = elf_path.read_bytes()
        regenerated = build_elf(program)
        if committed != regenerated:
            errors.append(f"{name}: committed ELF is not byte-identical to the generator output")
            continue
        if _sha256(committed) != vector["elf_sha256"]:
            errors.append(f"{name}: ELF digest drift")
            continue
        trace_bytes = dump_trace(dumper, elf_path, scratch / f"{name}.trace.json")
        if _sha256(trace_bytes) != vector["trace_sha256"]:
            errors.append(f"{name}: trace digest drift (executor semantics changed?)")
            continue
        trace = json.loads(trace_bytes)
        if trace["total_steps"] != vector["total_steps"]:
            errors.append(
                f"{name}: step count {trace['total_steps']} != recorded {vector['total_steps']}"
            )
        if trace["final_pc"] != vector["final_pc"]:
            errors.append(f"{name}: final pc {trace['final_pc']} != recorded {vector['final_pc']}")

    if errors:
        for error in errors:
            print(f"riscv trace vectors: {error}", file=sys.stderr)
        return 1
    print(
        f"riscv trace vectors: {len(payload['vectors'])} vectors verified against "
        f"stark-v {payload['stark_v_commit'][:8]}"
    )
    return 0


def validate_rust_source(rust_source: Path) -> str:
    """Require a clean Stark-V checkout at the repository's exact pin."""
    try:
        head = subprocess.run(
            ["git", "-C", str(rust_source), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        status = subprocess.run(
            ["git", "-C", str(rust_source), "status", "--porcelain"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as error:
        raise SystemExit(f"cannot inspect Stark-V source checkout: {error}") from error

    expected = pinned_stark_v_commit()
    if head != expected:
        raise SystemExit(f"Stark-V source is at {head}, expected exact pin {expected}")
    if status:
        raise SystemExit("Stark-V source checkout is dirty; refusing oracle attestation")
    return head


def attest_rust(rust_dumper: Path, rust_source: Path, scratch: Path) -> int:
    """Cross-run every vector and require identical canonical trace bytes."""
    source_commit = validate_rust_source(rust_source)
    rust_dumper = rust_dumper.resolve(strict=True)
    binary_sha256 = _sha256(rust_dumper.read_bytes())
    payload = json.loads(VECTOR_FILE.read_text(encoding="utf-8"))
    dumper = build_trace_dumper()
    for vector in payload["vectors"]:
        elf_path = ROOT / vector["elf"]
        zig_bytes = dump_trace(dumper, elf_path, scratch / f"{vector['name']}.zig.json")
        rust_out = subprocess.run(
            [str(rust_dumper), "--elf", str(elf_path)],
            cwd=ROOT,
            check=True,
            capture_output=True,
        )
        if rust_out.stdout != zig_bytes:
            print(
                f"riscv trace vectors: {vector['name']}: canonical bytes disagree "
                f"(rust {_sha256(rust_out.stdout)} vs zig {_sha256(zig_bytes)})",
                file=sys.stderr,
            )
            return 1
        if _sha256(zig_bytes) != vector["trace_sha256"]:
            print(
                f"riscv trace vectors: {vector['name']}: byte-identical oracle "
                "output disagrees with the committed digest",
                file=sys.stderr,
            )
            return 1
        print(f"{vector['name']}: rust/zig canonical trace bytes are identical")
    payload["cross_verification"] = {
        "tool": "scripts/riscv_trace_vectors.py --attest-rust",
        "status": "rust-cross-verified",
        "comparison": "canonical-json-byte-identical",
        "fields": ["steps", "final_pc", "final_regs", "total_steps"],
        "rust_source_commit": source_commit,
        "rust_binary_sha256": binary_sha256,
        "note": "every committed ELF produced identical canonical bytes in "
        "Zig and the Stark-V runner adapter; instruction clocks are one-based "
        "to match the pinned oracle",
    }
    VECTOR_FILE.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print(f"provenance escalated in {VECTOR_FILE}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="regenerate fixtures and digests")
    parser.add_argument("--attest-rust", type=Path, default=None, metavar="RUST_DUMPER",
                        help="cross-run vectors against a Stark-V dumper built at the "
                             "pinned commit and escalate provenance on agreement")
    parser.add_argument("--rust-source", type=Path, default=None, metavar="STARK_V_CHECKOUT",
                        help="clean Stark-V checkout at the exact pin (required with "
                             "--attest-rust)")
    parser.add_argument("--scratch", type=Path, default=None, help="working dir for trace output")
    args = parser.parse_args(argv)
    import tempfile

    def dispatch(scratch: Path) -> int:
        if args.update:
            return update(scratch)
        if args.attest_rust is not None:
            if args.rust_source is None:
                parser.error("--rust-source is required with --attest-rust")
            return attest_rust(args.attest_rust, args.rust_source, scratch)
        return gate(scratch)

    if args.scratch is not None:
        args.scratch.mkdir(parents=True, exist_ok=True)
        return dispatch(args.scratch)
    with tempfile.TemporaryDirectory() as tmp:
        return dispatch(Path(tmp))


if __name__ == "__main__":
    raise SystemExit(main())
