"""Scratch-harness generation: isolate code outside the repo and measure it."""

from __future__ import annotations

import os
import shutil
from pathlib import Path

ZIG_WORKLOAD_TEMPLATE = '''//! stwo-prof workload. Contract:
//!   - `run(seed)` performs one unit of work; `seed` is a RUNTIME value the
//!     harness threads through calls — fold your inputs from it, or LLVM
//!     will constant-evaluate a pure function of constants to O(1)
//!     (instructions/op near zero is the tell);
//!   - return a u64 derived from the work (defeats dead-code elimination);
//!   - set `ops_per_call` if one call is internally batched so per-op
//!     numbers stay honest;
//!   - keep the unit >= ~1us, or batch until it is, so call overhead
//!     cannot dominate what you measure.
pub const ops_per_call: u64 = 1024;

pub fn run(seed: u64) u64 {
    // Demo: xorshift chain from the runtime seed — serially dependent and
    // not constant-foldable.
    var state: u64 = seed | 1;
    var i: u64 = 0;
    while (i < ops_per_call) : (i += 1) {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
    }
    return state;
}
'''

ZIG_MAIN_TEMPLATE = '''//! Generated by stwo-prof. The harness measures the workload in-process:
//! wall time via std.time.Timer, and on macOS instructions / cycles /
//! energy via proc_pid_rusage(RUSAGE_INFO_V4) — counter deltas around the
//! measured loop, no profiler attach, no elevated privileges.
const std = @import("std");
const builtin = @import("builtin");
const workload = @import("workload.zig");

const RUsageInfoV4 = extern struct {
    ri_uuid: [16]u8,
    ri_user_time: u64,
    ri_system_time: u64,
    ri_pkg_idle_wkups: u64,
    ri_interrupt_wkups: u64,
    ri_pageins: u64,
    ri_wired_size: u64,
    ri_resident_size: u64,
    ri_phys_footprint: u64,
    ri_proc_start_abstime: u64,
    ri_proc_exit_abstime: u64,
    ri_child_user_time: u64,
    ri_child_system_time: u64,
    ri_child_pkg_idle_wkups: u64,
    ri_child_interrupt_wkups: u64,
    ri_child_pageins: u64,
    ri_child_elapsed_abstime: u64,
    ri_diskio_bytesread: u64,
    ri_diskio_byteswritten: u64,
    ri_cpu_time_qos_default: u64,
    ri_cpu_time_qos_maintenance: u64,
    ri_cpu_time_qos_background: u64,
    ri_cpu_time_qos_utility: u64,
    ri_cpu_time_qos_legacy: u64,
    ri_cpu_time_qos_user_initiated: u64,
    ri_cpu_time_qos_user_interactive: u64,
    ri_billed_system_time: u64,
    ri_serviced_system_time: u64,
    ri_logical_writes: u64,
    ri_lifetime_max_phys_footprint: u64,
    ri_instructions: u64,
    ri_cycles: u64,
    ri_billed_energy: u64,
    ri_serviced_energy: u64,
    ri_interval_max_phys_footprint: u64,
    ri_runnable_time: u64,
    ri_flags: u64,
};

extern "c" fn proc_pid_rusage(pid: c_int, flavor: c_int, buffer: *RUsageInfoV4) c_int;

fn counters() ?RUsageInfoV4 {
    if (builtin.os.tag != .macos) return null;
    var info: RUsageInfoV4 = undefined;
    if (proc_pid_rusage(std.c.getpid(), 4, &info) != 0) return null;
    return info;
}

fn envIters() u64 {
    const raw = std.posix.getenv("STWO_PROF_ITERS") orelse return 2000;
    return std.fmt.parseInt(u64, raw, 10) catch 2000;
}

pub fn main() !void {
    const iters = envIters();
    const warmup = @max(iters / 10, 8);

    var acc: u64 = 0;
    var w: u64 = 0;
    while (w < warmup) : (w += 1) acc = workload.run(acc +% w);
    std.mem.doNotOptimizeAway(acc);

    const before = counters();
    var timer = try std.time.Timer.start();
    acc = 0;
    var i: u64 = 0;
    while (i < iters) : (i += 1) acc = workload.run(acc +% i);
    const wall_ns = timer.read();
    const after = counters();
    std.mem.doNotOptimizeAway(acc);

    const ops: f64 = @floatFromInt(iters * workload.ops_per_call);
    const stdout = std.fs.File.stdout();
    var buffer: [1024]u8 = undefined;
    var writer = stdout.writer(&buffer);
    const out = &writer.interface;
    try out.print("{{\\"iterations\\":{d},\\"ops_per_call\\":{d},\\"wall_ns\\":{d},\\"ns_per_op\\":{d:.4}", .{
        iters, workload.ops_per_call, wall_ns, @as(f64, @floatFromInt(wall_ns)) / ops,
    });
    if (before != null and after != null) {
        const instr = after.?.ri_instructions - before.?.ri_instructions;
        const cyc = after.?.ri_cycles - before.?.ri_cycles;
        const energy = after.?.ri_billed_energy -| before.?.ri_billed_energy;
        const ipc = if (cyc == 0) 0.0 else @as(f64, @floatFromInt(instr)) / @as(f64, @floatFromInt(cyc));
        try out.print(",\\"instructions\\":{d},\\"cycles\\":{d},\\"ipc\\":{d:.3}", .{ instr, cyc, ipc });
        try out.print(",\\"instructions_per_op\\":{d:.3},\\"cycles_per_op\\":{d:.3},\\"energy_nj\\":{d}", .{
            @as(f64, @floatFromInt(instr)) / ops, @as(f64, @floatFromInt(cyc)) / ops, energy,
        });
        try out.print(",\\"peak_footprint_bytes\\":{d}", .{after.?.ri_lifetime_max_phys_footprint});
    }
    try out.print("}}\\n", .{});
    try out.flush();
}
'''

ZIG_BUILD_TEMPLATE = '''const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const module = b.createModule(.{
        .root_source_file = b.path("main.zig"),
        .target = target,
        .optimize = optimize,
    });
    const exe = b.addExecutable(.{ .name = "bench", .root_module = module });
    b.installArtifact(exe);
}
'''

METAL_KERNEL_TEMPLATE = '''// stwo-prof demo kernel. Replace with the kernel under investigation.
// The generic runner binds buffers in declaration order and fills them
// with deterministic data; buffer 0 is treated as the output.
#include <metal_stdlib>
using namespace metal;

kernel void demo_add(device float *out       [[buffer(0)]],
                     device const float *a   [[buffer(1)]],
                     device const float *b   [[buffer(2)]],
                     uint gid                [[thread_position_in_grid]]) {
    out[gid] = a[gid] + b[gid];
}
'''


def scratch_root() -> Path:
    base = os.environ.get("STWO_PROF_SCRATCH")
    root = Path(base) if base else Path.home() / ".cache" / "stwo-prof"
    root.mkdir(parents=True, exist_ok=True)
    return root


def resolve(name_or_path: str) -> Path:
    p = Path(name_or_path)
    if p.exists() or "/" in name_or_path:
        return p
    return scratch_root() / name_or_path


def isolate_zig(name: str, source: Path | None) -> Path:
    """Create (or refresh the harness of) a scratch Zig bench directory."""
    dest = scratch_root() / name
    dest.mkdir(parents=True, exist_ok=True)
    workload = dest / "workload.zig"
    if source is not None:
        shutil.copy2(source, workload)
    elif not workload.exists():
        workload.write_text(ZIG_WORKLOAD_TEMPLATE)
    (dest / "main.zig").write_text(ZIG_MAIN_TEMPLATE)
    (dest / "build.zig").write_text(ZIG_BUILD_TEMPLATE)
    return dest


def isolate_metal(name: str, source: Path | None) -> Path:
    dest = scratch_root() / name
    dest.mkdir(parents=True, exist_ok=True)
    kernel = dest / "kernel.metal"
    if source is not None:
        shutil.copy2(source, kernel)
    elif not kernel.exists():
        kernel.write_text(METAL_KERNEL_TEMPLATE)
    return dest
